In [1]:
from __future__ import print_function
from matplotlib import pyplot as plt
# get_ipython().magic(u'matplotlib auto')
import tensorflow as tf
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()
# import torch
from tensorflow import keras
import statistics

In [2]:
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Activation
from tensorflow import reshape
from keras.utils import np_utils
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling1D,AveragePooling1D
from tensorflow.keras.layers import Input, LocallyConnected1D
from tensorflow.keras.layers import SeparableConv1D, Bidirectional
from tensorflow.keras.layers import LocallyConnected2D
from tensorflow.keras.layers import ZeroPadding2D,ZeroPadding1D, MaxPooling2D, Bidirectional
from tensorflow.keras.regularizers import l2,l1
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import CSVLogger,LearningRateScheduler
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint

In [3]:
from scipy.io import loadmat
import numpy as np
import pandas as pd
import seaborn as sns
from numpy import mean
from numpy import std
# import coremltools
# from torch import nn, optim
# import torch.nn.functional as F
import scipy.io
from scipy import stats
#from IPython.display import display, HTML
from tensorflow.keras import optimizers
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import GRU
from tensorflow.keras.layers import TimeDistributed
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [4]:
# The number of steps within one time segment
TIME_PERIODS = 300
# The steps to take from one segment to the next; if this value is equal to
# TIME_PERIODS, then there is no overlap between the segments
STEP_DISTANCE = 300
N_FEATURES = 8

In [5]:
column_names = ['C'+str(j) for j in range(1, N_FEATURES+1)]
lst = ['Class_label']
column_names = column_names+lst
print(column_names)

['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'Class_label']


In [6]:
def read_data_Train(file_path_Train):
    df_Train = pd.read_csv(file_path_Train,header=None,names=column_names)
    # Last column has a ";" character which must be removed ...
    df_Train['Class_label'].replace(regex=True,inplace=True,to_replace=r';',value=r'')
    # ... and then this column must be transformed to float explicitly
    df_Train['Class_label'] = df_Train['Class_label'].apply(convert_to_float)
    # This is very important otherwise the model will not fit and loss
    # will show up as NAN
    df_Train.dropna(axis=0, how='any', inplace=True)
    return df_Train
def convert_to_float(x):
    try:
        return np.float(x)
    except:
        return np.nan

In [7]:
def show_basic_dataframe_info(dataframe):
    # Shape and how many rows and columns
    print('Number of columns in the dataframe: %i' % (dataframe.shape[1]))
    print('Number of rows in the dataframe: %i\n' % (dataframe.shape[0]))

In [8]:
def read_data_Test(file_path_Test):
    df_Test = pd.read_csv(file_path_Test,header=None,names=column_names)
    # Last column has a ";" character which must be removed ...
    df_Test['Class_label'].replace(regex=True,inplace=True,to_replace=r';',value=r'')
    # ... and then this column must be transformed to float explicitly
    df_Test['Class_label'] = df_Test['Class_label'].apply(convert_to_float)
    # This is very important otherwise the model will not fit and loss
    # will show up as NAN
    df_Test.dropna(axis=0, how='any', inplace=True)
    return df_Test

In [9]:
 pd.options.display.float_format = "{:,.5f}".format

In [10]:
# 15 function to segment data into trial lengths (trial length =513 samples in this dataset)
def create_segments_and_labels(df, time_steps,step,n_features, label_name):
    segments = []
    labels = []
    for i in range(0, len(df) - time_steps, step):
      for j in range(1, n_features+1):
        L = ('C'+str(j)) 
        segments.append(df[str(L)].values[i: i + time_steps])
      label = stats.mode(df[label_name][i: i + time_steps])[0][0]
      labels.append(label)
    reshaped_segments = np.asarray(segments, dtype= np.float32).reshape(-1, time_steps, n_features)
    labels = np.asarray(labels)
    return reshaped_segments, labels

In [11]:
verbose, epochs, batch_size = 0, 120, 32

In [12]:
def step_decay(epoch):
   initial_lrate = 1e-3
   drop = 0.1
   epochs_drop = 40.0
   lrate = initial_lrate * tf.math.pow(drop,  
           tf.math.floor((1+epoch)/epochs_drop))
   return lrate

In [13]:
lrate = tf.keras.callbacks.LearningRateScheduler(step_decay)
test_acc=[]

In [14]:
# import os
path='/media/naveen/nav/mat_codes/BioPatRec/prep_LP_wave/sub_wise_process_TT/'

In [15]:
def conv_block(input_data,n_channel):
    inputs=input_data
    print(inputs.shape)
    l_y=[]
    for i in range(0,n_channel):
        ip=inputs[:,:,i]
        print('ip_shape',ip.shape)
#         ip1=tf.convert_to_tensor(ip, dtype=tf.float32)
        ip=tf.reshape(ip,(tf.shape(ip)[0],300,1))
        print('ip_shape',ip.shape)
        x = Conv1D(64, kernel_size=3,kernel_initializer="he_normal",kernel_regularizer=l1(1e-04), \
               padding='same',input_shape=ip.shape)(ip)
        print('conv1_o',x.shape)
        x = BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x = Activation('relu')(x)
        x= Conv1D(filters=64, kernel_size=3,padding="same", kernel_regularizer=l2(5e-04),kernel_initializer="he_normal",strides=1)(x)
        x= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x= Activation('relu')(x)
        x= LocallyConnected1D(64, kernel_size=1, kernel_regularizer=l2(5e-04),kernel_initializer="he_normal",strides=1,padding='valid')(x)
        x= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x= Activation('relu')(x)
        x= LocallyConnected1D(64, kernel_size=1, kernel_regularizer=l2(5e-04),kernel_initializer="he_normal",strides=1,padding='valid')(x)
        x= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x= Activation('relu')(x)
        y= Dropout(0.5)(x)
        l_y.append(y)
    y_stack=tf.stack(l_y, axis=2)   
    return y_stack

In [16]:
n_length =  300
n_depth=8
n_channel=8
n_outputs=26

In [17]:
def generate_model():
    inputs = Input(shape=(n_length,n_depth),name="main")
    p=conv_block(inputs,8)
    print(p.shape)
    print(type(p))
#     print(y.shape)
    y=Flatten()(p)
    print(y.shape)
    y= Dense(512, kernel_initializer="he_normal")(y)
    y= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(y)
    y= Activation('relu')(y)
    y= Dropout(0.5)(y)
    y= Dense(512, kernel_initializer="he_normal")(y)
    y= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(y)
    y= Activation('relu')(y)
    y= Dropout(0.5)(y)
    y= Dense(128, kernel_initializer="he_normal")(y)
    y= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(y)
    y= Activation('relu')(y)
    outputs=Dense(n_outputs, activation='softmax')(y)
    print(outputs.shape)
#     wei_mscnn_model = Model(inputs,sub_inputs], outputs)
    print('inputs_shape',inputs.shape)
    final_model = Model(inputs,outputs,name="wei_mscnn_model")
    return final_model   

In [18]:
if __name__ == "__main__":
    model = generate_model()

(None, 300, 8)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
ip_shape (None, 300)
ip_shape (None, 300, 1)
conv1_o (None, 300, 64)
(None, 300, 8, 64)
<class 'tensorflow.python.framework.ops.Tensor'>
(None, 153600)
(None, 26)
inputs_shape (None, 300, 8)


In [19]:
for i in range(1,18):
    file_path_train=path+'S'+str(i)+'_'+'tr'+'.'+'csv'
    print(file_path_train)
    df_Train=read_data_Train(file_path_train)
    show_basic_dataframe_info(df_Train)
    df_Train.head(5)
    file_path_test=path+'S'+str(i)+'_'+'tt'+'.'+'csv'
    print(file_path_test)
    df_Test=read_data_Test(file_path_test)
    show_basic_dataframe_info(df_Test).;
    df_Test.head(5)
#     feature standardization
    scaler = preprocessing.StandardScaler().fit(df_Train.iloc[:,0:N_FEATURES])
    df_Train.iloc[:,0:N_FEATURES]=scaler.transform(df_Train.iloc[:,0:N_FEATURES])
    df_Test.iloc[:,0:N_FEATURES]=scaler.transform(df_Test.iloc[:,0:N_FEATURES])
    
    LABEL = 'ActivityEncoded'
    # Transform the labels from String to Integer via LabelEncoder
    le = preprocessing.LabelEncoder()
    # Add a new column to the existing DataFrame with the encoded values
    df_Train[LABEL] = le.fit_transform(df_Train['Class_label'].values.ravel())
    # df_Valid[LABEL] = le.fit_transform(df_Valid['Class_label'].values.ravel())
    df_Test[LABEL] = le.fit_transform(df_Test['Class_label'].values.ravel())
    x_train, y_train = create_segments_and_labels(df_Train,TIME_PERIODS,STEP_DISTANCE,N_FEATURES,LABEL)
    print('x_train shape: ', x_train.shape)
    # print(x_train)
    print(x_train.shape[0], 'training samples')
    print('y_train shape: ', y_train.shape)
    # Set input & output dimensions
    num_time_periods, num_sensors = x_train.shape[1], x_train.shape[2]
    print('num_time_periods',num_time_periods)
    print('num_sensors',num_sensors)
    num_classes = le.classes_.size
    print('class_list',list(le.classes_))
    # input_shape = (num_time_periods,num_sensors)
    # print(input_shape)
    input_shape = (num_time_periods,num_sensors)
    #x_train = x_train.reshape(x_train.shape[0], input_shape)
    print('x_train shape:', x_train[0].shape)
    print('input_shape:', input_shape)
    x_train = x_train.astype('float32')
    # x_train = [torch.tensor(arr, dtype=torch.float32) for arr in x_train]
    # y_train = y_train.astype('float32')
    # print(y_train)
    y_train_hot = np_utils.to_categorical(y_train, num_classes)
    print(y_train_hot)
    # y_train_hot= [torch.tensor(arr, dtype=torch.uint8) for arr in y_train_hot]
    print('New y_train shape: ', y_train_hot.shape)
    x_test, y_test = create_segments_and_labels(df_Test,TIME_PERIODS,STEP_DISTANCE,N_FEATURES,LABEL)
    print('x_test shape: ', x_test.shape)
    # print(x_train)
    print(x_test.shape[0], 'testing samples')
    print('y_test shape: ', y_test.shape)
    # Set input_shape / reshape for Keras
    #x_test = x_test.reshape(x_test.shape[0], input_shape)
    x_test = x_test.astype('float32')
    y_test = y_test.astype('float32')
    y_test_hot = np_utils.to_categorical(y_test, num_classes)
    # n_steps, n_length = 20, 25
    # n_steps, n_length= 10, 50
    # n_steps, n_length= 16, 32
    n_length =  300
    n_depth=8
    n_channel=8
    x_train = x_train.reshape(x_train.shape[0], n_length,n_depth)
    print('x_train shape: ', x_train.shape)
    # x_valid = x_valid.reshape(x_valid.shape[0], n_steps, n_length, n_depth)
    # print('x_valid shape: ', x_valid.shape)
    x_test = x_test.reshape(x_test.shape[0],  n_length,n_depth)
    print('x_test shape: ', x_test.shape)
    n_outputs = y_train_hot.shape[1]
    print('n_outputs',n_outputs)
    adam=optimizers.Adam(lr=1e-3, beta_1=0.9, beta_2=0.999, amsgrad=False)
#     sgd=optimizers.SGD(learning_rate=0.1, momentum=0.9, nesterov=False, name='SGD')
    checkpoint_filepath = '/media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5'
#     model.load_weights(checkpoint_filepath) 
    checkpoint_callback = ModelCheckpoint(filepath=checkpoint_filepath,verbose=1, monitor='val_accuracy',save_weights_only=True,save_best_only=True)
    early = EarlyStopping(monitor='val_loss', min_delta=0, patience=100, verbose=0, mode='auto', baseline=None, restore_best_weights=True)
    model.compile(optimizer=adam,loss='categorical_crossentropy',metrics=['accuracy'])
    print(model.summary())
#     tf.keras.utils.plot_model(model, to_file='/media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/olsson/CNN20X10/Model1.png',show_shapes=True,show_layer_names=True,dpi=96)
    csv_logger = CSVLogger('/media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/LSTM_nina_20X100.csv', append=True, separator=';')
    history = model.fit(x_train, y_train_hot, epochs=epochs, batch_size=batch_size, callbacks=[csv_logger,checkpoint_callback,lrate,early],validation_data=(x_test, y_test_hot), verbose=1)
    best_index = history.history['val_accuracy'].index(max(history.history['val_accuracy']))
    print('epoch_number',best_index+1)
    print('train accuracy and validation accuracy', history.history['accuracy'][best_index], history.history['val_accuracy'][best_index])
    model.load_weights(checkpoint_filepath) 
    _, testaccuracy = model.evaluate(x_test, y_test_hot, batch_size=batch_size, verbose=1)
    print('test_accuracy',testaccuracy)
    test_acc.append(testaccuracy)
    print(test_acc)
    test_mean=statistics.mean(test_acc)
    print('test_mean for %d subjects:',i)
    print(test_mean)

/media/naveen/nav/mat_codes/BioPatRec/prep_LP_wave/sub_wise_process_TT/S1_tr.csv
Number of columns in the dataframe: 9
Number of rows in the dataframe: 312000

/media/naveen/nav/mat_codes/BioPatRec/prep_LP_wave/sub_wise_process_TT/S1_tt.csv
Number of columns in the dataframe: 9
Number of rows in the dataframe: 156000

x_train shape:  (1039, 300, 8)
1039 training samples
y_train shape:  (1039,)
num_time_periods 300
num_sensors 8
class_list [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0]
x_train shape: (300, 8)
input_shape: (300, 8)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
New y_train shape:  (1039, 26)
x_test shape:  (519, 300, 8)
519 testing samples
y_test shape:  (519,)
x_train shape:  (1039, 300, 8)
x_test shape:  (519, 300, 8)
n_outputs 26
Model: "wei_mscnn_model"
_______

33/33 [==============================] - ETA: 0s - loss: 4.7379 - accuracy: 0.1396
Epoch 00001: val_accuracy improved from -inf to 0.08863, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 50s 2s/step - loss: 4.7379 - accuracy: 0.1396 - val_loss: 4.8373 - val_accuracy: 0.0886 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 3.9889 - accuracy: 0.3359
Epoch 00002: val_accuracy improved from 0.08863 to 0.42197, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 243ms/step - loss: 3.9889 - accuracy: 0.3359 - val_loss: 3.7297 - val_accuracy: 0.4220 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 3.3411 - accuracy: 0.4629
Epoch 00003: val_accuracy improved from 0.42197 to 0.49711, saving model to /media/naveen/nav/mat_codes/nina_DB1

Epoch 27/120
33/33 [==============================] - ETA: 0s - loss: 0.9722 - accuracy: 0.8720
Epoch 00027: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 161ms/step - loss: 0.9722 - accuracy: 0.8720 - val_loss: 2.1121 - val_accuracy: 0.5299 - lr: 0.0010
Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.9559 - accuracy: 0.8643
Epoch 00028: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 159ms/step - loss: 0.9559 - accuracy: 0.8643 - val_loss: 1.9396 - val_accuracy: 0.5800 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.9300 - accuracy: 0.8778
Epoch 00029: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 158ms/step - loss: 0.9300 - accuracy: 0.8778 - val_loss: 1.8920 - val_accuracy: 0.5934 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.9381 - accuracy: 0.8730
Epoch 00030: val_ac

Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.6522 - accuracy: 0.9278
Epoch 00055: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 160ms/step - loss: 0.6522 - accuracy: 0.9278 - val_loss: 2.0128 - val_accuracy: 0.5568 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.6709 - accuracy: 0.9124
Epoch 00056: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 162ms/step - loss: 0.6709 - accuracy: 0.9124 - val_loss: 1.9646 - val_accuracy: 0.5723 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.6520 - accuracy: 0.9220
Epoch 00057: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 158ms/step - loss: 0.6520 - accuracy: 0.9220 - val_loss: 1.9687 - val_accuracy: 0.5761 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.6591 - accuracy: 0.9192
Epoch 0

Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.5526 - accuracy: 0.9278
Epoch 00083: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 162ms/step - loss: 0.5526 - accuracy: 0.9278 - val_loss: 1.9845 - val_accuracy: 0.5645 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.5580 - accuracy: 0.9288
Epoch 00084: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 159ms/step - loss: 0.5580 - accuracy: 0.9288 - val_loss: 1.9656 - val_accuracy: 0.5588 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.5577 - accuracy: 0.9249
Epoch 00085: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 161ms/step - loss: 0.5577 - accuracy: 0.9249 - val_loss: 1.9726 - val_accuracy: 0.5723 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.5623 - accuracy: 0.9230
Epoch 0

Epoch 111/120
33/33 [==============================] - ETA: 0s - loss: 0.5434 - accuracy: 0.9259
Epoch 00111: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 160ms/step - loss: 0.5434 - accuracy: 0.9259 - val_loss: 1.9560 - val_accuracy: 0.5645 - lr: 1.0000e-05
Epoch 112/120
33/33 [==============================] - ETA: 0s - loss: 0.5494 - accuracy: 0.9259
Epoch 00112: val_accuracy did not improve from 0.62813
33/33 [==============================] - 5s 157ms/step - loss: 0.5494 - accuracy: 0.9259 - val_loss: 1.9399 - val_accuracy: 0.5703 - lr: 1.0000e-05
Epoch 113/120
33/33 [==============================] - ETA: 0s - loss: 0.5531 - accuracy: 0.9288
Epoch 00113: val_accuracy did not improve from 0.62813
33/33 [==============================] - 6s 167ms/step - loss: 0.5531 - accuracy: 0.9288 - val_loss: 1.9919 - val_accuracy: 0.5511 - lr: 1.0000e-05
epoch_number 6
train accuracy and validation accuracy 0.751684308052063 0.6281310319900513
17/17 [==

33/33 [==============================] - ETA: 0s - loss: 2.7803 - accuracy: 0.4129
Epoch 00001: val_accuracy improved from -inf to 0.59730, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 36s 1s/step - loss: 2.7803 - accuracy: 0.4129 - val_loss: 2.1004 - val_accuracy: 0.5973 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.9674 - accuracy: 0.6718
Epoch 00002: val_accuracy improved from 0.59730 to 0.63198, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 252ms/step - loss: 1.9674 - accuracy: 0.6718 - val_loss: 2.0267 - val_accuracy: 0.6320 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.6511 - accuracy: 0.7719
Epoch 00003: val_accuracy improved from 0.63198 to 0.66859, saving model to /media/naveen/nav/mat_codes/nina_DB1

Epoch 27/120
33/33 [==============================] - ETA: 0s - loss: 0.7220 - accuracy: 0.9451
Epoch 00027: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 157ms/step - loss: 0.7220 - accuracy: 0.9451 - val_loss: 1.5795 - val_accuracy: 0.6821 - lr: 0.0010
Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.7000 - accuracy: 0.9596
Epoch 00028: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 162ms/step - loss: 0.7000 - accuracy: 0.9596 - val_loss: 1.6455 - val_accuracy: 0.6802 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.6823 - accuracy: 0.9586
Epoch 00029: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 159ms/step - loss: 0.6823 - accuracy: 0.9586 - val_loss: 1.5907 - val_accuracy: 0.6994 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.6641 - accuracy: 0.9557
Epoch 00030: val_ac

Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.4273 - accuracy: 0.9923
Epoch 00055: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 161ms/step - loss: 0.4273 - accuracy: 0.9923 - val_loss: 1.4038 - val_accuracy: 0.7013 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.4259 - accuracy: 0.9904
Epoch 00056: val_accuracy did not improve from 0.71869
33/33 [==============================] - 6s 173ms/step - loss: 0.4259 - accuracy: 0.9904 - val_loss: 1.3915 - val_accuracy: 0.7013 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.4246 - accuracy: 0.9913
Epoch 00057: val_accuracy did not improve from 0.71869
33/33 [==============================] - 6s 173ms/step - loss: 0.4246 - accuracy: 0.9913 - val_loss: 1.3559 - val_accuracy: 0.7071 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.4015 - accuracy: 0.9923
Epoch 0

Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.3191 - accuracy: 0.9933
Epoch 00083: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 157ms/step - loss: 0.3191 - accuracy: 0.9933 - val_loss: 1.3318 - val_accuracy: 0.7091 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.3118 - accuracy: 0.9923
Epoch 00084: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 161ms/step - loss: 0.3118 - accuracy: 0.9923 - val_loss: 1.3162 - val_accuracy: 0.7129 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.3166 - accuracy: 0.9942
Epoch 00085: val_accuracy did not improve from 0.71869
33/33 [==============================] - 5s 158ms/step - loss: 0.3166 - accuracy: 0.9942 - val_loss: 1.3033 - val_accuracy: 0.7168 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.3140 - accuracy: 0.9952
Epoch 0

Epoch 110/120
33/33 [==============================] - ETA: 0s - loss: 0.3008 - accuracy: 0.9952
Epoch 00110: val_accuracy did not improve from 0.73025
33/33 [==============================] - 5s 166ms/step - loss: 0.3008 - accuracy: 0.9952 - val_loss: 1.3193 - val_accuracy: 0.7110 - lr: 1.0000e-05
Epoch 111/120
33/33 [==============================] - ETA: 0s - loss: 0.2989 - accuracy: 0.9942
Epoch 00111: val_accuracy did not improve from 0.73025
33/33 [==============================] - 6s 184ms/step - loss: 0.2989 - accuracy: 0.9942 - val_loss: 1.2820 - val_accuracy: 0.7225 - lr: 1.0000e-05
Epoch 112/120
33/33 [==============================] - ETA: 0s - loss: 0.2921 - accuracy: 0.9981
Epoch 00112: val_accuracy did not improve from 0.73025
33/33 [==============================] - 5s 155ms/step - loss: 0.2921 - accuracy: 0.9981 - val_loss: 1.2872 - val_accuracy: 0.7091 - lr: 1.0000e-05
Epoch 113/120
33/33 [==============================] - ETA: 0s - loss: 0.2998 - accuracy: 0.9962
Epo

33/33 [==============================] - ETA: 0s - loss: 3.5834 - accuracy: 0.3927
Epoch 00001: val_accuracy improved from -inf to 0.57611, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 35s 1s/step - loss: 3.5834 - accuracy: 0.3927 - val_loss: 2.1646 - val_accuracy: 0.5761 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.7736 - accuracy: 0.6458
Epoch 00002: val_accuracy improved from 0.57611 to 0.73603, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 9s 268ms/step - loss: 1.7736 - accuracy: 0.6458 - val_loss: 1.5304 - val_accuracy: 0.7360 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.3986 - accuracy: 0.7584
Epoch 00003: val_accuracy did not improve from 0.73603
33/33 [==============================] - 6s 187ms/step - 

33/33 [==============================] - ETA: 0s - loss: 0.4107 - accuracy: 0.9913
Epoch 00055: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 157ms/step - loss: 0.4107 - accuracy: 0.9913 - val_loss: 1.5545 - val_accuracy: 0.7264 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.4048 - accuracy: 0.9904
Epoch 00056: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 159ms/step - loss: 0.4048 - accuracy: 0.9904 - val_loss: 1.5282 - val_accuracy: 0.7129 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.3975 - accuracy: 0.9913
Epoch 00057: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 158ms/step - loss: 0.3975 - accuracy: 0.9913 - val_loss: 1.5338 - val_accuracy: 0.7245 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.3987 - accuracy: 0.9865
Epoch 00058: val_acc

Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.3059 - accuracy: 0.9913
Epoch 00083: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 162ms/step - loss: 0.3059 - accuracy: 0.9913 - val_loss: 1.4653 - val_accuracy: 0.7148 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.2952 - accuracy: 0.9981
Epoch 00084: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 158ms/step - loss: 0.2952 - accuracy: 0.9981 - val_loss: 1.4689 - val_accuracy: 0.7225 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.2992 - accuracy: 0.9962
Epoch 00085: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 157ms/step - loss: 0.2992 - accuracy: 0.9962 - val_loss: 1.4679 - val_accuracy: 0.7206 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.2942 - accuracy: 0.9981
Epoch 0

Epoch 111/120
33/33 [==============================] - ETA: 0s - loss: 0.2874 - accuracy: 0.9971
Epoch 00111: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 167ms/step - loss: 0.2874 - accuracy: 0.9971 - val_loss: 1.4433 - val_accuracy: 0.7148 - lr: 1.0000e-05
Epoch 112/120
33/33 [==============================] - ETA: 0s - loss: 0.2862 - accuracy: 0.9971
Epoch 00112: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 160ms/step - loss: 0.2862 - accuracy: 0.9971 - val_loss: 1.4529 - val_accuracy: 0.7225 - lr: 1.0000e-05
Epoch 113/120
33/33 [==============================] - ETA: 0s - loss: 0.2855 - accuracy: 0.9962
Epoch 00113: val_accuracy did not improve from 0.73796
33/33 [==============================] - 6s 172ms/step - loss: 0.2855 - accuracy: 0.9962 - val_loss: 1.4348 - val_accuracy: 0.7245 - lr: 1.0000e-05
Epoch 114/120
33/33 [==============================] - ETA: 0s - loss: 0.2827 - accuracy: 0.9981
Epo

33/33 [==============================] - ETA: 0s - loss: 3.8193 - accuracy: 0.3301
Epoch 00001: val_accuracy improved from -inf to 0.54335, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 1s/step - loss: 3.8193 - accuracy: 0.3301 - val_loss: 2.0812 - val_accuracy: 0.5434 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 2.0413 - accuracy: 0.5813
Epoch 00002: val_accuracy improved from 0.54335 to 0.67245, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 254ms/step - loss: 2.0413 - accuracy: 0.5813 - val_loss: 1.6239 - val_accuracy: 0.6724 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.7032 - accuracy: 0.6872
Epoch 00003: val_accuracy improved from 0.67245 to 0.69750, saving model to /media/naveen/nav/mat_codes/nina_DB1

Epoch 27/120
33/33 [==============================] - ETA: 0s - loss: 0.8646 - accuracy: 0.9018
Epoch 00027: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 160ms/step - loss: 0.8646 - accuracy: 0.9018 - val_loss: 1.6442 - val_accuracy: 0.6782 - lr: 0.0010
Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.8845 - accuracy: 0.8912
Epoch 00028: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 158ms/step - loss: 0.8845 - accuracy: 0.8912 - val_loss: 1.6911 - val_accuracy: 0.6513 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.8389 - accuracy: 0.8999
Epoch 00029: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 158ms/step - loss: 0.8389 - accuracy: 0.8999 - val_loss: 1.7171 - val_accuracy: 0.6474 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.8478 - accuracy: 0.8932
Epoch 00030: val_ac

Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.5374 - accuracy: 0.9538
Epoch 00055: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 158ms/step - loss: 0.5374 - accuracy: 0.9538 - val_loss: 1.6163 - val_accuracy: 0.6455 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.5464 - accuracy: 0.9509
Epoch 00056: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 161ms/step - loss: 0.5464 - accuracy: 0.9509 - val_loss: 1.6088 - val_accuracy: 0.6513 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.5470 - accuracy: 0.9490
Epoch 00057: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 159ms/step - loss: 0.5470 - accuracy: 0.9490 - val_loss: 1.5773 - val_accuracy: 0.6667 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.5515 - accuracy: 0.9403
Epoch 0

Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.4421 - accuracy: 0.9557
Epoch 00083: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 157ms/step - loss: 0.4421 - accuracy: 0.9557 - val_loss: 1.6029 - val_accuracy: 0.6397 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.4308 - accuracy: 0.9605
Epoch 00084: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 160ms/step - loss: 0.4308 - accuracy: 0.9605 - val_loss: 1.5841 - val_accuracy: 0.6474 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.4294 - accuracy: 0.9567
Epoch 00085: val_accuracy did not improve from 0.70906
33/33 [==============================] - 5s 158ms/step - loss: 0.4294 - accuracy: 0.9567 - val_loss: 1.5720 - val_accuracy: 0.6493 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.4445 - accuracy: 0.9567
Epoch 0

Number of columns in the dataframe: 9
Number of rows in the dataframe: 312000

/media/naveen/nav/mat_codes/BioPatRec/prep_LP_wave/sub_wise_process_TT/S5_tt.csv
Number of columns in the dataframe: 9
Number of rows in the dataframe: 156000

x_train shape:  (1039, 300, 8)
1039 training samples
y_train shape:  (1039,)
num_time_periods 300
num_sensors 8
class_list [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0]
x_train shape: (300, 8)
input_shape: (300, 8)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
New y_train shape:  (1039, 26)
x_test shape:  (519, 300, 8)
519 testing samples
y_test shape:  (519,)
x_train shape:  (1039, 300, 8)
x_test shape:  (519, 300, 8)
n_outputs 26
Model: "wei_mscnn_model"
________________________________________________________________________________________

33/33 [==============================] - ETA: 0s - loss: 4.2342 - accuracy: 0.2551
Epoch 00001: val_accuracy improved from -inf to 0.56262, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 34s 1s/step - loss: 4.2342 - accuracy: 0.2551 - val_loss: 1.9297 - val_accuracy: 0.5626 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.8045 - accuracy: 0.6198
Epoch 00002: val_accuracy improved from 0.56262 to 0.75723, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 251ms/step - loss: 1.8045 - accuracy: 0.6198 - val_loss: 1.4540 - val_accuracy: 0.7572 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.3822 - accuracy: 0.7478
Epoch 00003: val_accuracy improved from 0.75723 to 0.77842, saving model to /media/naveen/nav/mat_codes/nina_DB1

Epoch 53/120
33/33 [==============================] - ETA: 0s - loss: 0.4581 - accuracy: 0.9596
Epoch 00053: val_accuracy improved from 0.82274 to 0.82659, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 252ms/step - loss: 0.4581 - accuracy: 0.9596 - val_loss: 0.9228 - val_accuracy: 0.8266 - lr: 1.0000e-04
Epoch 54/120
33/33 [==============================] - ETA: 0s - loss: 0.4378 - accuracy: 0.9625
Epoch 00054: val_accuracy improved from 0.82659 to 0.82852, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 247ms/step - loss: 0.4378 - accuracy: 0.9625 - val_loss: 0.9196 - val_accuracy: 0.8285 - lr: 1.0000e-04
Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.4437 - accuracy: 0.9567
Epoch 00055: val_accuracy did not improve from 0.82852
33/33 [======================

Epoch 80/120
33/33 [==============================] - ETA: 0s - loss: 0.3364 - accuracy: 0.9692
Epoch 00080: val_accuracy did not improve from 0.82852
33/33 [==============================] - 5s 165ms/step - loss: 0.3364 - accuracy: 0.9692 - val_loss: 0.8959 - val_accuracy: 0.7996 - lr: 1.0000e-05
Epoch 81/120
33/33 [==============================] - ETA: 0s - loss: 0.3314 - accuracy: 0.9731
Epoch 00081: val_accuracy did not improve from 0.82852
33/33 [==============================] - 5s 163ms/step - loss: 0.3314 - accuracy: 0.9731 - val_loss: 0.8996 - val_accuracy: 0.8092 - lr: 1.0000e-05
Epoch 82/120
33/33 [==============================] - ETA: 0s - loss: 0.3218 - accuracy: 0.9731
Epoch 00082: val_accuracy did not improve from 0.82852
33/33 [==============================] - 5s 160ms/step - loss: 0.3218 - accuracy: 0.9731 - val_loss: 0.8815 - val_accuracy: 0.8054 - lr: 1.0000e-05
Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.3302 - accuracy: 0.9682
Epoch 0

Epoch 108/120
33/33 [==============================] - ETA: 0s - loss: 0.3203 - accuracy: 0.9702
Epoch 00108: val_accuracy did not improve from 0.82852
33/33 [==============================] - 5s 162ms/step - loss: 0.3203 - accuracy: 0.9702 - val_loss: 0.8617 - val_accuracy: 0.8112 - lr: 1.0000e-05
Epoch 109/120
33/33 [==============================] - ETA: 0s - loss: 0.3186 - accuracy: 0.9711
Epoch 00109: val_accuracy did not improve from 0.82852
33/33 [==============================] - 5s 160ms/step - loss: 0.3186 - accuracy: 0.9711 - val_loss: 0.8814 - val_accuracy: 0.8054 - lr: 1.0000e-05
Epoch 110/120
33/33 [==============================] - ETA: 0s - loss: 0.3026 - accuracy: 0.9759
Epoch 00110: val_accuracy did not improve from 0.82852
33/33 [==============================] - 5s 164ms/step - loss: 0.3026 - accuracy: 0.9759 - val_loss: 0.8939 - val_accuracy: 0.8015 - lr: 1.0000e-05
Epoch 111/120
33/33 [==============================] - ETA: 0s - loss: 0.3172 - accuracy: 0.9682
Epo

dense_2 (Dense)                 (None, 128)          65664       dropout_9[0][0]                  
__________________________________________________________________________________________________
batch_normalization_34 (BatchNo (None, 128)          512         dense_2[0][0]                    
__________________________________________________________________________________________________
activation_34 (Activation)      (None, 128)          0           batch_normalization_34[0][0]     
__________________________________________________________________________________________________
dense_3 (Dense)                 (None, 26)           3354        activation_34[0][0]              
Total params: 99,057,050
Trainable params: 99,050,650
Non-trainable params: 6,400
__________________________________________________________________________________________________
None
Epoch 1/120
33/33 [==============================] - ETA: 0s - loss: 4.5631 - accuracy: 0.1992
Epoch 00001: val_accuracy 

Epoch 23/120
33/33 [==============================] - ETA: 0s - loss: 1.1939 - accuracy: 0.8441
Epoch 00023: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 163ms/step - loss: 1.1939 - accuracy: 0.8441 - val_loss: 2.6597 - val_accuracy: 0.5260 - lr: 0.0010
Epoch 24/120
33/33 [==============================] - ETA: 0s - loss: 1.1445 - accuracy: 0.8576
Epoch 00024: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 161ms/step - loss: 1.1445 - accuracy: 0.8576 - val_loss: 2.5310 - val_accuracy: 0.5607 - lr: 0.0010
Epoch 25/120
33/33 [==============================] - ETA: 0s - loss: 1.1223 - accuracy: 0.8585
Epoch 00025: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 161ms/step - loss: 1.1223 - accuracy: 0.8585 - val_loss: 2.7305 - val_accuracy: 0.5318 - lr: 0.0010
Epoch 26/120
33/33 [==============================] - ETA: 0s - loss: 1.0844 - accuracy: 0.8633
Epoch 00026: val_ac

Epoch 51/120
33/33 [==============================] - ETA: 0s - loss: 0.6604 - accuracy: 0.9451
Epoch 00051: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 160ms/step - loss: 0.6604 - accuracy: 0.9451 - val_loss: 2.6699 - val_accuracy: 0.5164 - lr: 1.0000e-04
Epoch 52/120
33/33 [==============================] - ETA: 0s - loss: 0.6625 - accuracy: 0.9384
Epoch 00052: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 159ms/step - loss: 0.6625 - accuracy: 0.9384 - val_loss: 2.6857 - val_accuracy: 0.5183 - lr: 1.0000e-04
Epoch 53/120
33/33 [==============================] - ETA: 0s - loss: 0.6417 - accuracy: 0.9538
Epoch 00053: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 159ms/step - loss: 0.6417 - accuracy: 0.9538 - val_loss: 2.6649 - val_accuracy: 0.5260 - lr: 1.0000e-04
Epoch 54/120
33/33 [==============================] - ETA: 0s - loss: 0.6310 - accuracy: 0.9500
Epoch 0

Epoch 79/120
33/33 [==============================] - ETA: 0s - loss: 0.4690 - accuracy: 0.9682
Epoch 00079: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 163ms/step - loss: 0.4690 - accuracy: 0.9682 - val_loss: 2.7796 - val_accuracy: 0.4990 - lr: 1.0000e-04
Epoch 80/120
33/33 [==============================] - ETA: 0s - loss: 0.4578 - accuracy: 0.9682
Epoch 00080: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 161ms/step - loss: 0.4578 - accuracy: 0.9682 - val_loss: 2.7232 - val_accuracy: 0.5010 - lr: 1.0000e-05
Epoch 81/120
33/33 [==============================] - ETA: 0s - loss: 0.4672 - accuracy: 0.9682
Epoch 00081: val_accuracy did not improve from 0.56455
33/33 [==============================] - 5s 160ms/step - loss: 0.4672 - accuracy: 0.9682 - val_loss: 2.7443 - val_accuracy: 0.4971 - lr: 1.0000e-05
Epoch 82/120
33/33 [==============================] - ETA: 0s - loss: 0.4560 - accuracy: 0.9692
Epoch 0

Epoch 1/120
33/33 [==============================] - ETA: 0s - loss: 3.2532 - accuracy: 0.3224
Epoch 00001: val_accuracy improved from -inf to 0.57996, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 1s/step - loss: 3.2532 - accuracy: 0.3224 - val_loss: 1.9820 - val_accuracy: 0.5800 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.9840 - accuracy: 0.6054
Epoch 00002: val_accuracy improved from 0.57996 to 0.68015, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 241ms/step - loss: 1.9840 - accuracy: 0.6054 - val_loss: 1.7009 - val_accuracy: 0.6802 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.6683 - accuracy: 0.6891
Epoch 00003: val_accuracy improved from 0.68015 to 0.70328, saving model to /media/naveen/nav/mat_co

33/33 [==============================] - ETA: 0s - loss: 0.5677 - accuracy: 0.9461
Epoch 00053: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 156ms/step - loss: 0.5677 - accuracy: 0.9461 - val_loss: 1.4080 - val_accuracy: 0.7225 - lr: 1.0000e-04
Epoch 54/120
33/33 [==============================] - ETA: 0s - loss: 0.5611 - accuracy: 0.9480
Epoch 00054: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 159ms/step - loss: 0.5611 - accuracy: 0.9480 - val_loss: 1.3814 - val_accuracy: 0.7225 - lr: 1.0000e-04
Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.5447 - accuracy: 0.9471
Epoch 00055: val_accuracy did not improve from 0.74374
33/33 [==============================] - 6s 170ms/step - loss: 0.5447 - accuracy: 0.9471 - val_loss: 1.3590 - val_accuracy: 0.7168 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.5647 - accuracy: 0.9365
Epoch 00056: val_acc

Epoch 81/120
33/33 [==============================] - ETA: 0s - loss: 0.4373 - accuracy: 0.9596
Epoch 00081: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 159ms/step - loss: 0.4373 - accuracy: 0.9596 - val_loss: 1.4067 - val_accuracy: 0.7110 - lr: 1.0000e-05
Epoch 82/120
33/33 [==============================] - ETA: 0s - loss: 0.4304 - accuracy: 0.9528
Epoch 00082: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 158ms/step - loss: 0.4304 - accuracy: 0.9528 - val_loss: 1.3950 - val_accuracy: 0.7206 - lr: 1.0000e-05
Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.4160 - accuracy: 0.9567
Epoch 00083: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 158ms/step - loss: 0.4160 - accuracy: 0.9567 - val_loss: 1.3912 - val_accuracy: 0.7110 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.4216 - accuracy: 0.9577
Epoch 0

Epoch 109/120
33/33 [==============================] - ETA: 0s - loss: 0.4097 - accuracy: 0.9615
Epoch 00109: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 158ms/step - loss: 0.4097 - accuracy: 0.9615 - val_loss: 1.3883 - val_accuracy: 0.7245 - lr: 1.0000e-05
Epoch 110/120
33/33 [==============================] - ETA: 0s - loss: 0.4077 - accuracy: 0.9548
Epoch 00110: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 157ms/step - loss: 0.4077 - accuracy: 0.9548 - val_loss: 1.3816 - val_accuracy: 0.7110 - lr: 1.0000e-05
Epoch 111/120
33/33 [==============================] - ETA: 0s - loss: 0.4166 - accuracy: 0.9577
Epoch 00111: val_accuracy did not improve from 0.74374
33/33 [==============================] - 5s 158ms/step - loss: 0.4166 - accuracy: 0.9577 - val_loss: 1.3968 - val_accuracy: 0.7091 - lr: 1.0000e-05
Epoch 112/120
33/33 [==============================] - ETA: 0s - loss: 0.3997 - accuracy: 0.9673
Epo

33/33 [==============================] - ETA: 0s - loss: 4.7994 - accuracy: 0.1906
Epoch 00001: val_accuracy improved from -inf to 0.40848, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 999ms/step - loss: 4.7994 - accuracy: 0.1906 - val_loss: 2.8652 - val_accuracy: 0.4085 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 2.5172 - accuracy: 0.4524
Epoch 00002: val_accuracy improved from 0.40848 to 0.53757, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 244ms/step - loss: 2.5172 - accuracy: 0.4524 - val_loss: 2.2502 - val_accuracy: 0.5376 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.9805 - accuracy: 0.5861
Epoch 00003: val_accuracy improved from 0.53757 to 0.55106, saving model to /media/naveen/nav/mat_codes/nina_

Epoch 27/120
33/33 [==============================] - ETA: 0s - loss: 0.8193 - accuracy: 0.9278
Epoch 00027: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 159ms/step - loss: 0.8193 - accuracy: 0.9278 - val_loss: 2.1886 - val_accuracy: 0.5838 - lr: 0.0010
Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.8063 - accuracy: 0.9288
Epoch 00028: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 160ms/step - loss: 0.8063 - accuracy: 0.9288 - val_loss: 2.3116 - val_accuracy: 0.5549 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.8484 - accuracy: 0.9057
Epoch 00029: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 161ms/step - loss: 0.8484 - accuracy: 0.9057 - val_loss: 2.3862 - val_accuracy: 0.5434 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.8446 - accuracy: 0.9211
Epoch 00030: val_ac

Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.5817 - accuracy: 0.9798
Epoch 00055: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 156ms/step - loss: 0.5817 - accuracy: 0.9798 - val_loss: 2.1706 - val_accuracy: 0.5665 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.5786 - accuracy: 0.9779
Epoch 00056: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 158ms/step - loss: 0.5786 - accuracy: 0.9779 - val_loss: 2.1874 - val_accuracy: 0.5761 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.5804 - accuracy: 0.9740
Epoch 00057: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 158ms/step - loss: 0.5804 - accuracy: 0.9740 - val_loss: 2.1907 - val_accuracy: 0.5723 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.5515 - accuracy: 0.9856
Epoch 0

Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.4202 - accuracy: 0.9894
Epoch 00083: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 160ms/step - loss: 0.4202 - accuracy: 0.9894 - val_loss: 2.1486 - val_accuracy: 0.5607 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.4362 - accuracy: 0.9817
Epoch 00084: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 160ms/step - loss: 0.4362 - accuracy: 0.9817 - val_loss: 2.1407 - val_accuracy: 0.5549 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.4359 - accuracy: 0.9798
Epoch 00085: val_accuracy did not improve from 0.59923
33/33 [==============================] - 5s 158ms/step - loss: 0.4359 - accuracy: 0.9798 - val_loss: 2.1180 - val_accuracy: 0.5665 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.4388 - accuracy: 0.9836
Epoch 0

33/33 [==============================] - ETA: 0s - loss: 4.0122 - accuracy: 0.2233
Epoch 00001: val_accuracy improved from -inf to 0.40462, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 34s 1s/step - loss: 4.0122 - accuracy: 0.2233 - val_loss: 2.6365 - val_accuracy: 0.4046 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 2.2752 - accuracy: 0.5111
Epoch 00002: val_accuracy improved from 0.40462 to 0.49904, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 252ms/step - loss: 2.2752 - accuracy: 0.5111 - val_loss: 2.1421 - val_accuracy: 0.4990 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.8315 - accuracy: 0.6420
Epoch 00003: val_accuracy improved from 0.49904 to 0.53179, saving model to /media/naveen/nav/mat_codes/nina_DB1

Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.9736 - accuracy: 0.8989
Epoch 00028: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 159ms/step - loss: 0.9736 - accuracy: 0.8989 - val_loss: 2.3715 - val_accuracy: 0.4913 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.8909 - accuracy: 0.9076
Epoch 00029: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 160ms/step - loss: 0.8909 - accuracy: 0.9076 - val_loss: 2.3942 - val_accuracy: 0.4740 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.9233 - accuracy: 0.8951
Epoch 00030: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 157ms/step - loss: 0.9233 - accuracy: 0.8951 - val_loss: 2.4477 - val_accuracy: 0.5106 - lr: 0.0010
Epoch 31/120
33/33 [==============================] - ETA: 0s - loss: 0.9219 - accuracy: 0.8922
Epoch 00031: val_ac

Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.6013 - accuracy: 0.9586
Epoch 00056: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 162ms/step - loss: 0.6013 - accuracy: 0.9586 - val_loss: 2.4961 - val_accuracy: 0.4971 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.5640 - accuracy: 0.9702
Epoch 00057: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 158ms/step - loss: 0.5640 - accuracy: 0.9702 - val_loss: 2.4960 - val_accuracy: 0.4990 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.5748 - accuracy: 0.9615
Epoch 00058: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 158ms/step - loss: 0.5748 - accuracy: 0.9615 - val_loss: 2.4536 - val_accuracy: 0.4990 - lr: 1.0000e-04
Epoch 59/120
33/33 [==============================] - ETA: 0s - loss: 0.5631 - accuracy: 0.9673
Epoch 0

Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.4369 - accuracy: 0.9750
Epoch 00084: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 155ms/step - loss: 0.4369 - accuracy: 0.9750 - val_loss: 2.5220 - val_accuracy: 0.4855 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.4349 - accuracy: 0.9740
Epoch 00085: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 160ms/step - loss: 0.4349 - accuracy: 0.9740 - val_loss: 2.5063 - val_accuracy: 0.4990 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.4273 - accuracy: 0.9759
Epoch 00086: val_accuracy did not improve from 0.57611
33/33 [==============================] - 5s 157ms/step - loss: 0.4273 - accuracy: 0.9759 - val_loss: 2.5250 - val_accuracy: 0.4778 - lr: 1.0000e-05
Epoch 87/120
33/33 [==============================] - ETA: 0s - loss: 0.4414 - accuracy: 0.9721
Epoch 0

33/33 [==============================] - ETA: 0s - loss: 2.9466 - accuracy: 0.3725
Epoch 00001: val_accuracy improved from -inf to 0.46821, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 992ms/step - loss: 2.9466 - accuracy: 0.3725 - val_loss: 2.2919 - val_accuracy: 0.4682 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.9559 - accuracy: 0.5871
Epoch 00002: val_accuracy improved from 0.46821 to 0.58960, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 247ms/step - loss: 1.9559 - accuracy: 0.5871 - val_loss: 1.9536 - val_accuracy: 0.5896 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.5820 - accuracy: 0.6968
Epoch 00003: val_accuracy did not improve from 0.58960
33/33 [==============================] - 5s 158ms/step

Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.7812 - accuracy: 0.9394
Epoch 00028: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 160ms/step - loss: 0.7812 - accuracy: 0.9394 - val_loss: 2.0180 - val_accuracy: 0.5838 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.7698 - accuracy: 0.9365
Epoch 00029: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 156ms/step - loss: 0.7698 - accuracy: 0.9365 - val_loss: 2.3089 - val_accuracy: 0.5530 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.7646 - accuracy: 0.9365
Epoch 00030: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 159ms/step - loss: 0.7646 - accuracy: 0.9365 - val_loss: 2.2988 - val_accuracy: 0.5877 - lr: 0.0010
Epoch 31/120
33/33 [==============================] - ETA: 0s - loss: 0.7605 - accuracy: 0.9451
Epoch 00031: val_ac

Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.4978 - accuracy: 0.9817
Epoch 00056: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 159ms/step - loss: 0.4978 - accuracy: 0.9817 - val_loss: 2.1760 - val_accuracy: 0.5761 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.4923 - accuracy: 0.9817
Epoch 00057: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 159ms/step - loss: 0.4923 - accuracy: 0.9817 - val_loss: 2.1528 - val_accuracy: 0.5954 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.4881 - accuracy: 0.9817
Epoch 00058: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 159ms/step - loss: 0.4881 - accuracy: 0.9817 - val_loss: 2.1521 - val_accuracy: 0.5838 - lr: 1.0000e-04
Epoch 59/120
33/33 [==============================] - ETA: 0s - loss: 0.4763 - accuracy: 0.9846
Epoch 0

Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.3609 - accuracy: 0.9904
Epoch 00084: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 158ms/step - loss: 0.3609 - accuracy: 0.9904 - val_loss: 2.0816 - val_accuracy: 0.5780 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.3713 - accuracy: 0.9885
Epoch 00085: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 158ms/step - loss: 0.3713 - accuracy: 0.9885 - val_loss: 2.1616 - val_accuracy: 0.5915 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.3696 - accuracy: 0.9836
Epoch 00086: val_accuracy did not improve from 0.59538
33/33 [==============================] - 5s 160ms/step - loss: 0.3696 - accuracy: 0.9836 - val_loss: 2.1118 - val_accuracy: 0.5761 - lr: 1.0000e-05
Epoch 87/120
33/33 [==============================] - ETA: 0s - loss: 0.3755 - accuracy: 0.9817
Epoch 0

33/33 [==============================] - ETA: 0s - loss: 2.8238 - accuracy: 0.3446
Epoch 00001: val_accuracy improved from -inf to 0.55491, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 994ms/step - loss: 2.8238 - accuracy: 0.3446 - val_loss: 2.0598 - val_accuracy: 0.5549 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.8947 - accuracy: 0.6131
Epoch 00002: val_accuracy improved from 0.55491 to 0.59538, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 249ms/step - loss: 1.8947 - accuracy: 0.6131 - val_loss: 1.8494 - val_accuracy: 0.5954 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.5119 - accuracy: 0.7161
Epoch 00003: val_accuracy improved from 0.59538 to 0.63391, saving model to /media/naveen/nav/mat_codes/nina_

Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.8310 - accuracy: 0.9336
Epoch 00028: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 159ms/step - loss: 0.8310 - accuracy: 0.9336 - val_loss: 2.2480 - val_accuracy: 0.6089 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.8321 - accuracy: 0.9201
Epoch 00029: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 166ms/step - loss: 0.8321 - accuracy: 0.9201 - val_loss: 2.0231 - val_accuracy: 0.6281 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.7751 - accuracy: 0.9259
Epoch 00030: val_accuracy did not improve from 0.66474
33/33 [==============================] - 6s 170ms/step - loss: 0.7751 - accuracy: 0.9259 - val_loss: 2.0221 - val_accuracy: 0.6281 - lr: 0.0010
Epoch 31/120
33/33 [==============================] - ETA: 0s - loss: 0.7529 - accuracy: 0.9423
Epoch 00031: val_ac

Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.5141 - accuracy: 0.9769
Epoch 00056: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 162ms/step - loss: 0.5141 - accuracy: 0.9769 - val_loss: 2.0626 - val_accuracy: 0.6281 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.4979 - accuracy: 0.9836
Epoch 00057: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 160ms/step - loss: 0.4979 - accuracy: 0.9836 - val_loss: 2.0757 - val_accuracy: 0.6281 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.5003 - accuracy: 0.9808
Epoch 00058: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 161ms/step - loss: 0.5003 - accuracy: 0.9808 - val_loss: 2.0575 - val_accuracy: 0.6435 - lr: 1.0000e-04
Epoch 59/120
33/33 [==============================] - ETA: 0s - loss: 0.4801 - accuracy: 0.9827
Epoch 0

Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.3742 - accuracy: 0.9875
Epoch 00084: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 156ms/step - loss: 0.3742 - accuracy: 0.9875 - val_loss: 2.0448 - val_accuracy: 0.6069 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.3621 - accuracy: 0.9894
Epoch 00085: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 157ms/step - loss: 0.3621 - accuracy: 0.9894 - val_loss: 2.0357 - val_accuracy: 0.6089 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.3708 - accuracy: 0.9875
Epoch 00086: val_accuracy did not improve from 0.66474
33/33 [==============================] - 5s 158ms/step - loss: 0.3708 - accuracy: 0.9875 - val_loss: 2.0325 - val_accuracy: 0.6146 - lr: 1.0000e-05
Epoch 87/120
33/33 [==============================] - ETA: 0s - loss: 0.3614 - accuracy: 0.9885
Epoch 0

33/33 [==============================] - ETA: 0s - loss: 2.6906 - accuracy: 0.4273
Epoch 00001: val_accuracy improved from -inf to 0.68208, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 1000ms/step - loss: 2.6906 - accuracy: 0.4273 - val_loss: 1.5585 - val_accuracy: 0.6821 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.4882 - accuracy: 0.7372
Epoch 00002: val_accuracy improved from 0.68208 to 0.78420, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 243ms/step - loss: 1.4882 - accuracy: 0.7372 - val_loss: 1.2864 - val_accuracy: 0.7842 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.1613 - accuracy: 0.8316
Epoch 00003: val_accuracy did not improve from 0.78420
33/33 [==============================] - 6s 171ms/ste

Epoch 27/120
33/33 [==============================] - ETA: 0s - loss: 0.5437 - accuracy: 0.9721
Epoch 00027: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 159ms/step - loss: 0.5437 - accuracy: 0.9721 - val_loss: 1.2110 - val_accuracy: 0.7765 - lr: 0.0010
Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.5693 - accuracy: 0.9548
Epoch 00028: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 157ms/step - loss: 0.5693 - accuracy: 0.9548 - val_loss: 1.2011 - val_accuracy: 0.7919 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.5407 - accuracy: 0.9692
Epoch 00029: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 155ms/step - loss: 0.5407 - accuracy: 0.9692 - val_loss: 1.2234 - val_accuracy: 0.7784 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.4958 - accuracy: 0.9788
Epoch 00030: val_ac

Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.3512 - accuracy: 0.9933
Epoch 00055: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 159ms/step - loss: 0.3512 - accuracy: 0.9933 - val_loss: 1.1125 - val_accuracy: 0.7919 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.3474 - accuracy: 0.9923
Epoch 00056: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 157ms/step - loss: 0.3474 - accuracy: 0.9923 - val_loss: 1.1085 - val_accuracy: 0.7958 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.3483 - accuracy: 0.9923
Epoch 00057: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 160ms/step - loss: 0.3483 - accuracy: 0.9923 - val_loss: 1.1232 - val_accuracy: 0.7958 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.3323 - accuracy: 0.9962
Epoch 0

33/33 [==============================] - 6s 171ms/step - loss: 0.2483 - accuracy: 0.9942 - val_loss: 1.0213 - val_accuracy: 0.8035 - lr: 1.0000e-05
Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.2399 - accuracy: 0.9981
Epoch 00083: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 158ms/step - loss: 0.2399 - accuracy: 0.9981 - val_loss: 1.0364 - val_accuracy: 0.8035 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.2398 - accuracy: 0.9962
Epoch 00084: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 156ms/step - loss: 0.2398 - accuracy: 0.9962 - val_loss: 1.0521 - val_accuracy: 0.7938 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.2493 - accuracy: 0.9933
Epoch 00085: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 162ms/step - loss: 0.2493 - accuracy: 0.9933 - val_loss: 1.

Epoch 110/120
33/33 [==============================] - ETA: 0s - loss: 0.2296 - accuracy: 0.9990
Epoch 00110: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 162ms/step - loss: 0.2296 - accuracy: 0.9990 - val_loss: 1.0350 - val_accuracy: 0.7919 - lr: 1.0000e-05
Epoch 111/120
33/33 [==============================] - ETA: 0s - loss: 0.2279 - accuracy: 0.9971
Epoch 00111: val_accuracy did not improve from 0.81696
33/33 [==============================] - 6s 167ms/step - loss: 0.2279 - accuracy: 0.9971 - val_loss: 1.0557 - val_accuracy: 0.7938 - lr: 1.0000e-05
Epoch 112/120
33/33 [==============================] - ETA: 0s - loss: 0.2374 - accuracy: 0.9933
Epoch 00112: val_accuracy did not improve from 0.81696
33/33 [==============================] - 5s 157ms/step - loss: 0.2374 - accuracy: 0.9933 - val_loss: 1.0548 - val_accuracy: 0.7919 - lr: 1.0000e-05
Epoch 113/120
33/33 [==============================] - ETA: 0s - loss: 0.2293 - accuracy: 0.9981
Epo

33/33 [==============================] - ETA: 0s - loss: 3.5722 - accuracy: 0.3359
Epoch 00001: val_accuracy improved from -inf to 0.48555, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 32s 979ms/step - loss: 3.5722 - accuracy: 0.3359 - val_loss: 2.5305 - val_accuracy: 0.4855 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 2.0721 - accuracy: 0.5582
Epoch 00002: val_accuracy improved from 0.48555 to 0.56262, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 236ms/step - loss: 2.0721 - accuracy: 0.5582 - val_loss: 1.9582 - val_accuracy: 0.5626 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.7139 - accuracy: 0.6535
Epoch 00003: val_accuracy improved from 0.56262 to 0.61079, saving model to /media/naveen/nav/mat_codes/nina_

Epoch 27/120
33/33 [==============================] - ETA: 0s - loss: 1.0029 - accuracy: 0.8787
Epoch 00027: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 152ms/step - loss: 1.0029 - accuracy: 0.8787 - val_loss: 2.4140 - val_accuracy: 0.5260 - lr: 0.0010
Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.9915 - accuracy: 0.8826
Epoch 00028: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 150ms/step - loss: 0.9915 - accuracy: 0.8826 - val_loss: 2.2325 - val_accuracy: 0.5723 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.9984 - accuracy: 0.8749
Epoch 00029: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 150ms/step - loss: 0.9984 - accuracy: 0.8749 - val_loss: 2.2598 - val_accuracy: 0.5588 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.9667 - accuracy: 0.8922
Epoch 00030: val_ac

Epoch 55/120
33/33 [==============================] - ETA: 0s - loss: 0.6402 - accuracy: 0.9269
Epoch 00055: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 151ms/step - loss: 0.6402 - accuracy: 0.9269 - val_loss: 2.1359 - val_accuracy: 0.5838 - lr: 1.0000e-04
Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.6272 - accuracy: 0.9384
Epoch 00056: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 150ms/step - loss: 0.6272 - accuracy: 0.9384 - val_loss: 2.1442 - val_accuracy: 0.5780 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.6170 - accuracy: 0.9432
Epoch 00057: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 151ms/step - loss: 0.6170 - accuracy: 0.9432 - val_loss: 2.1029 - val_accuracy: 0.5934 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.6176 - accuracy: 0.9394
Epoch 0

Epoch 83/120
33/33 [==============================] - ETA: 0s - loss: 0.5043 - accuracy: 0.9423
Epoch 00083: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 150ms/step - loss: 0.5043 - accuracy: 0.9423 - val_loss: 2.0723 - val_accuracy: 0.5934 - lr: 1.0000e-05
Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.5278 - accuracy: 0.9384
Epoch 00084: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 152ms/step - loss: 0.5278 - accuracy: 0.9384 - val_loss: 2.0664 - val_accuracy: 0.5973 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.4906 - accuracy: 0.9451
Epoch 00085: val_accuracy did not improve from 0.63006
33/33 [==============================] - 5s 152ms/step - loss: 0.4906 - accuracy: 0.9451 - val_loss: 2.0789 - val_accuracy: 0.5838 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.4756 - accuracy: 0.9480
Epoch 0

33/33 [==============================] - ETA: 0s - loss: 2.2006 - accuracy: 0.5294
Epoch 00001: val_accuracy improved from -inf to 0.73796, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 989ms/step - loss: 2.2006 - accuracy: 0.5294 - val_loss: 1.5085 - val_accuracy: 0.7380 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 1.3463 - accuracy: 0.7757
Epoch 00002: val_accuracy did not improve from 0.73796
33/33 [==============================] - 5s 163ms/step - loss: 1.3463 - accuracy: 0.7757 - val_loss: 1.3749 - val_accuracy: 0.7380 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.2017 - accuracy: 0.8075
Epoch 00003: val_accuracy improved from 0.73796 to 0.75723, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 240ms/step

Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.6124 - accuracy: 0.9374
Epoch 00028: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 152ms/step - loss: 0.6124 - accuracy: 0.9374 - val_loss: 1.3098 - val_accuracy: 0.7534 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.6207 - accuracy: 0.9317
Epoch 00029: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 154ms/step - loss: 0.6207 - accuracy: 0.9317 - val_loss: 1.2648 - val_accuracy: 0.7572 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.5828 - accuracy: 0.9471
Epoch 00030: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 153ms/step - loss: 0.5828 - accuracy: 0.9471 - val_loss: 1.4034 - val_accuracy: 0.7457 - lr: 0.0010
Epoch 31/120
33/33 [==============================] - ETA: 0s - loss: 0.5826 - accuracy: 0.9336
Epoch 00031: val_ac

Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.3606 - accuracy: 0.9788
Epoch 00056: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 153ms/step - loss: 0.3606 - accuracy: 0.9788 - val_loss: 1.2749 - val_accuracy: 0.7611 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.3741 - accuracy: 0.9682
Epoch 00057: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 155ms/step - loss: 0.3741 - accuracy: 0.9682 - val_loss: 1.3127 - val_accuracy: 0.7592 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.3569 - accuracy: 0.9788
Epoch 00058: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 153ms/step - loss: 0.3569 - accuracy: 0.9788 - val_loss: 1.2975 - val_accuracy: 0.7553 - lr: 1.0000e-04
Epoch 59/120
33/33 [==============================] - ETA: 0s - loss: 0.3528 - accuracy: 0.9788
Epoch 0

Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.2810 - accuracy: 0.9808
Epoch 00084: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 152ms/step - loss: 0.2810 - accuracy: 0.9808 - val_loss: 1.3009 - val_accuracy: 0.7457 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.2603 - accuracy: 0.9885
Epoch 00085: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 151ms/step - loss: 0.2603 - accuracy: 0.9885 - val_loss: 1.3083 - val_accuracy: 0.7457 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.2709 - accuracy: 0.9836
Epoch 00086: val_accuracy did not improve from 0.77649
33/33 [==============================] - 5s 152ms/step - loss: 0.2709 - accuracy: 0.9836 - val_loss: 1.3059 - val_accuracy: 0.7476 - lr: 1.0000e-05
Epoch 87/120
33/33 [==============================] - ETA: 0s - loss: 0.2649 - accuracy: 0.9856
Epoch 0

x_train shape:  (1039, 300, 8)
1039 training samples
y_train shape:  (1039,)
num_time_periods 300
num_sensors 8
class_list [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0]
x_train shape: (300, 8)
input_shape: (300, 8)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
New y_train shape:  (1039, 26)
x_test shape:  (519, 300, 8)
519 testing samples
y_test shape:  (519,)
x_train shape:  (1039, 300, 8)
x_test shape:  (519, 300, 8)
n_outputs 26
Model: "wei_mscnn_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main (InputLayer)               [(None, 300, 8)]     0                                            
______________________________

33/33 [==============================] - ETA: 0s - loss: 3.8988 - accuracy: 0.2579
Epoch 00001: val_accuracy improved from -inf to 0.41040, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 32s 975ms/step - loss: 3.8988 - accuracy: 0.2579 - val_loss: 2.4951 - val_accuracy: 0.4104 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 2.2087 - accuracy: 0.4822
Epoch 00002: val_accuracy improved from 0.41040 to 0.47592, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 232ms/step - loss: 2.2087 - accuracy: 0.4822 - val_loss: 2.1083 - val_accuracy: 0.4759 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.8921 - accuracy: 0.5746
Epoch 00003: val_accuracy improved from 0.47592 to 0.50674, saving model to /media/naveen/nav/mat_codes/nina_

Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 1.0603 - accuracy: 0.8614
Epoch 00028: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 162ms/step - loss: 1.0603 - accuracy: 0.8614 - val_loss: 2.7714 - val_accuracy: 0.4335 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 1.0678 - accuracy: 0.8595
Epoch 00029: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 163ms/step - loss: 1.0678 - accuracy: 0.8595 - val_loss: 2.6731 - val_accuracy: 0.4432 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 1.0522 - accuracy: 0.8556
Epoch 00030: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 157ms/step - loss: 1.0522 - accuracy: 0.8556 - val_loss: 2.7555 - val_accuracy: 0.4528 - lr: 0.0010
Epoch 31/120
33/33 [==============================] - ETA: 0s - loss: 1.0285 - accuracy: 0.8758
Epoch 00031: val_ac

Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.7199 - accuracy: 0.9230
Epoch 00056: val_accuracy did not improve from 0.52216
33/33 [==============================] - 6s 172ms/step - loss: 0.7199 - accuracy: 0.9230 - val_loss: 2.6376 - val_accuracy: 0.4566 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.6982 - accuracy: 0.9269
Epoch 00057: val_accuracy did not improve from 0.52216
33/33 [==============================] - 6s 167ms/step - loss: 0.6982 - accuracy: 0.9269 - val_loss: 2.6305 - val_accuracy: 0.4547 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.6975 - accuracy: 0.9230
Epoch 00058: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 164ms/step - loss: 0.6975 - accuracy: 0.9230 - val_loss: 2.5905 - val_accuracy: 0.4509 - lr: 1.0000e-04
Epoch 59/120
33/33 [==============================] - ETA: 0s - loss: 0.7008 - accuracy: 0.9172
Epoch 0

Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.5753 - accuracy: 0.9326
Epoch 00084: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 160ms/step - loss: 0.5753 - accuracy: 0.9326 - val_loss: 2.6189 - val_accuracy: 0.4566 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.5647 - accuracy: 0.9336
Epoch 00085: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 159ms/step - loss: 0.5647 - accuracy: 0.9336 - val_loss: 2.6321 - val_accuracy: 0.4682 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.5615 - accuracy: 0.9355
Epoch 00086: val_accuracy did not improve from 0.52216
33/33 [==============================] - 5s 159ms/step - loss: 0.5615 - accuracy: 0.9355 - val_loss: 2.6988 - val_accuracy: 0.4316 - lr: 1.0000e-05
Epoch 87/120
33/33 [==============================] - ETA: 0s - loss: 0.5470 - accuracy: 0.9413
Epoch 0

33/33 [==============================] - ETA: 0s - loss: 3.1808 - accuracy: 0.2868
Epoch 00001: val_accuracy improved from -inf to 0.38728, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 33s 994ms/step - loss: 3.1808 - accuracy: 0.2868 - val_loss: 2.5150 - val_accuracy: 0.3873 - lr: 0.0010
Epoch 2/120
33/33 [==============================] - ETA: 0s - loss: 2.2397 - accuracy: 0.4937
Epoch 00002: val_accuracy improved from 0.38728 to 0.43160, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_BPR_20X10/checkpoint.hdf5
33/33 [==============================] - 8s 256ms/step - loss: 2.2397 - accuracy: 0.4937 - val_loss: 2.2750 - val_accuracy: 0.4316 - lr: 0.0010
Epoch 3/120
33/33 [==============================] - ETA: 0s - loss: 1.8133 - accuracy: 0.6160
Epoch 00003: val_accuracy improved from 0.43160 to 0.46050, saving model to /media/naveen/nav/mat_codes/nina_

Epoch 28/120
33/33 [==============================] - ETA: 0s - loss: 0.9410 - accuracy: 0.8932
Epoch 00028: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 154ms/step - loss: 0.9410 - accuracy: 0.8932 - val_loss: 2.9882 - val_accuracy: 0.4451 - lr: 0.0010
Epoch 29/120
33/33 [==============================] - ETA: 0s - loss: 0.9543 - accuracy: 0.8826
Epoch 00029: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 156ms/step - loss: 0.9543 - accuracy: 0.8826 - val_loss: 3.1156 - val_accuracy: 0.4547 - lr: 0.0010
Epoch 30/120
33/33 [==============================] - ETA: 0s - loss: 0.9509 - accuracy: 0.8826
Epoch 00030: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 157ms/step - loss: 0.9509 - accuracy: 0.8826 - val_loss: 3.3708 - val_accuracy: 0.4066 - lr: 0.0010
Epoch 31/120
33/33 [==============================] - ETA: 0s - loss: 1.0164 - accuracy: 0.8701
Epoch 00031: val_ac

Epoch 56/120
33/33 [==============================] - ETA: 0s - loss: 0.5757 - accuracy: 0.9471
Epoch 00056: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 156ms/step - loss: 0.5757 - accuracy: 0.9471 - val_loss: 3.0452 - val_accuracy: 0.4412 - lr: 1.0000e-04
Epoch 57/120
33/33 [==============================] - ETA: 0s - loss: 0.5807 - accuracy: 0.9451
Epoch 00057: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 156ms/step - loss: 0.5807 - accuracy: 0.9451 - val_loss: 3.0307 - val_accuracy: 0.4451 - lr: 1.0000e-04
Epoch 58/120
33/33 [==============================] - ETA: 0s - loss: 0.5509 - accuracy: 0.9596
Epoch 00058: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 158ms/step - loss: 0.5509 - accuracy: 0.9596 - val_loss: 3.0600 - val_accuracy: 0.4393 - lr: 1.0000e-04
Epoch 59/120
33/33 [==============================] - ETA: 0s - loss: 0.5406 - accuracy: 0.9538
Epoch 0

Epoch 84/120
33/33 [==============================] - ETA: 0s - loss: 0.4713 - accuracy: 0.9519
Epoch 00084: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 158ms/step - loss: 0.4713 - accuracy: 0.9519 - val_loss: 3.0133 - val_accuracy: 0.4547 - lr: 1.0000e-05
Epoch 85/120
33/33 [==============================] - ETA: 0s - loss: 0.4182 - accuracy: 0.9702
Epoch 00085: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 155ms/step - loss: 0.4182 - accuracy: 0.9702 - val_loss: 3.0473 - val_accuracy: 0.4528 - lr: 1.0000e-05
Epoch 86/120
33/33 [==============================] - ETA: 0s - loss: 0.4364 - accuracy: 0.9692
Epoch 00086: val_accuracy did not improve from 0.46628
33/33 [==============================] - 5s 157ms/step - loss: 0.4364 - accuracy: 0.9692 - val_loss: 3.0533 - val_accuracy: 0.4528 - lr: 1.0000e-05
Epoch 87/120
33/33 [==============================] - ETA: 0s - loss: 0.4252 - accuracy: 0.9682
Epoch 0

In [20]:
statistics.mean(test_acc)

0.6618497092276812