In [1]:
from __future__ import print_function
from matplotlib import pyplot as plt
# get_ipython().magic(u'matplotlib auto')
import tensorflow as tf
# import tensorflow.compat.v1 as tf
# tf.disable_v2_behavior()
# import torch
from tensorflow import keras
import statistics

In [2]:
from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape
from tensorflow.keras.layers import Conv2D, MaxPooling2D,Activation
from tensorflow import reshape
from keras.utils import np_utils
from tensorflow.keras.layers import Conv1D,Conv2D, MaxPooling1D,AveragePooling1D
from tensorflow.keras.layers import Input, LocallyConnected1D
from tensorflow.keras.layers import SeparableConv1D, Bidirectional
from tensorflow.keras.layers import LocallyConnected2D
from tensorflow.keras.layers import ZeroPadding2D,ZeroPadding1D, MaxPooling2D, Bidirectional
from tensorflow.keras.regularizers import l2,l1
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.callbacks import CSVLogger,LearningRateScheduler
from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint

In [3]:
from scipy.io import loadmat
import numpy as np
import pandas as pd
import seaborn as sns
from numpy import mean
from numpy import std
# import coremltools
# from torch import nn, optim
# import torch.nn.functional as F
import scipy.io
from scipy import stats
#from IPython.display import display, HTML
from tensorflow.keras import optimizers
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import GRU
from tensorflow.keras.layers import TimeDistributed
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn import preprocessing

In [4]:
# The number of steps within one time segment
TIME_PERIODS = 400
# The steps to take from one segment to the next; if this value is equal to
# TIME_PERIODS, then there is no overlap between the segments
STEP_DISTANCE = 400
N_FEATURES = 12

In [5]:
column_names = ['C'+str(j) for j in range(1, N_FEATURES+1)]
lst = ['Class_label']
column_names = column_names+lst
print(column_names)

['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8', 'C9', 'C10', 'C11', 'C12', 'Class_label']


In [6]:
def read_data_Train(file_path_Train):
    df_Train = pd.read_csv(file_path_Train,header=None,names=column_names)
    # Last column has a ";" character which must be removed ...
    df_Train['Class_label'].replace(regex=True,inplace=True,to_replace=r';',value=r'')
    # ... and then this column must be transformed to float explicitly
    df_Train['Class_label'] = df_Train['Class_label'].apply(convert_to_float)
    # This is very important otherwise the model will not fit and loss
    # will show up as NAN
    df_Train.dropna(axis=0, how='any', inplace=True)
    return df_Train
def convert_to_float(x):
    try:
        return np.float(x)
    except:
        return np.nan

In [7]:
def show_basic_dataframe_info(dataframe):
    # Shape and how many rows and columns
    print('Number of columns in the dataframe: %i' % (dataframe.shape[1]))
    print('Number of rows in the dataframe: %i\n' % (dataframe.shape[0]))

In [8]:
def read_data_Test(file_path_Test):
    df_Test = pd.read_csv(file_path_Test,header=None,names=column_names)
    # Last column has a ";" character which must be removed ...
    df_Test['Class_label'].replace(regex=True,inplace=True,to_replace=r';',value=r'')
    # ... and then this column must be transformed to float explicitly
    df_Test['Class_label'] = df_Test['Class_label'].apply(convert_to_float)
    # This is very important otherwise the model will not fit and loss
    # will show up as NAN
    df_Test.dropna(axis=0, how='any', inplace=True)
    return df_Test

In [9]:
 pd.options.display.float_format = "{:,.5f}".format

In [10]:
# 15 function to segment data into trial lengths (trial length =513 samples in this dataset)
def create_segments_and_labels(df, time_steps,step,n_features, label_name):
    segments = []
    labels = []
    for i in range(0, len(df) - time_steps, step):
      for j in range(1, n_features+1):
        L = ('C'+str(j)) 
        segments.append(df[str(L)].values[i: i + time_steps])
      label = stats.mode(df[label_name][i: i + time_steps])[0][0]
      labels.append(label)
    reshaped_segments = np.asarray(segments, dtype= np.float32).reshape(-1, time_steps, n_features)
    labels = np.asarray(labels)
    return reshaped_segments, labels

In [11]:
verbose, epochs, batch_size = 0, 120, 32

In [12]:
def step_decay(epoch):
   initial_lrate = 1e-3
   drop = 0.1
   epochs_drop = 40.0
   lrate = initial_lrate * tf.math.pow(drop,  
           tf.math.floor((1+epoch)/epochs_drop))
   return lrate

In [13]:
lrate = tf.keras.callbacks.LearningRateScheduler(step_decay)
test_acc=[]

In [14]:
# import os
path='/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/'

In [15]:
def conv_block(input_data,n_channel):
    inputs=input_data
    print(inputs.shape)
    l_y=[]
    for i in range(0,n_channel):
        ip=inputs[:,:,i]
        print('ip_shape',ip.shape)
#         ip1=tf.convert_to_tensor(ip, dtype=tf.float32)
        ip=tf.reshape(ip,(tf.shape(ip)[0],400,1))
        print('ip_shape',ip.shape)
        x = Conv1D(64, kernel_size=3,kernel_initializer="he_normal",kernel_regularizer=l1(1e-04), \
               padding='same',input_shape=ip.shape)(ip)
        print('conv1_o',x.shape)
        x = BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x = Activation('relu')(x)
        x= Conv1D(filters=64, kernel_size=3,padding="same", kernel_regularizer=l2(5e-04),kernel_initializer="he_normal",strides=1)(x)
        x= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x= Activation('relu')(x)
        x= LocallyConnected1D(64, kernel_size=1, kernel_regularizer=l2(5e-04),kernel_initializer="he_normal",strides=1,padding='valid')(x)
        x= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x= Activation('relu')(x)
        x= LocallyConnected1D(64, kernel_size=1, kernel_regularizer=l2(5e-04),kernel_initializer="he_normal",strides=1,padding='valid')(x)
        x= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(x)
        x= Activation('relu')(x)
        y= Dropout(0.5)(x)
        l_y.append(y)
    y_stack=tf.stack(l_y, axis=2)   
    return y_stack

In [16]:
n_length =  400
n_depth=12
n_channel=12
n_outputs=52

In [17]:
def generate_model():
    inputs = Input(shape=(n_length,n_depth),name="main")
    p=conv_block(inputs,12)
    print(p.shape)
    print(type(p))
#     print(y.shape)
    y=Flatten()(p)
    print(y.shape)
    y= Dense(512, kernel_initializer="he_normal")(y)
    y= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(y)
    y= Activation('relu')(y)
    y= Dropout(0.5)(y)
    y= Dense(512, kernel_initializer="he_normal")(y)
    y= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(y)
    y= Activation('relu')(y)
    y= Dropout(0.5)(y)
    y= Dense(128, kernel_initializer="he_normal")(y)
    y= BatchNormalization(epsilon=1e-06, momentum=0.9, weights=None)(y)
    y= Activation('relu')(y)
    outputs=Dense(n_outputs, activation='softmax')(y)
    print(outputs.shape)
#     wei_mscnn_model = Model(inputs,sub_inputs], outputs)
    print('inputs_shape',inputs.shape)
    final_model = Model(inputs,outputs,name="wei_mscnn_model")
    return final_model   

In [18]:
if __name__ == "__main__":
    model = generate_model()

(None, 400, 12)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
ip_shape (None, 400)
ip_shape (None, 400, 1)
conv1_o (None, 400, 64)
(None, 400, 12, 64)
<class 'tensorflow.python.framework.ops.Tensor'>
(None, 307200)
(None, 52)
inputs_shape (None, 400, 12)


In [19]:
for i in range(1,11):
    file_path_train=path+'S'+str(i)+'_'+'tr'+'.'+'csv'
    print(file_path_train)
    df_Train=read_data_Train(file_path_train)
    show_basic_dataframe_info(df_Train)
    df_Train.head(5)
    file_path_test=path+'S'+str(i)+'_'+'tt'+'.'+'csv'
    print(file_path_test)
    df_Test=read_data_Test(file_path_test)
    show_basic_dataframe_info(df_Test)
    df_Test.head(5)
#     feature standardization
    scaler = preprocessing.StandardScaler().fit(df_Train.iloc[:,0:N_FEATURES])
    df_Train.iloc[:,0:N_FEATURES]=scaler.transform(df_Train.iloc[:,0:N_FEATURES])
    df_Test.iloc[:,0:N_FEATURES]=scaler.transform(df_Test.iloc[:,0:N_FEATURES])
    
    LABEL = 'ActivityEncoded'
    # Transform the labels from String to Integer via LabelEncoder
    le = preprocessing.LabelEncoder()
    # Add a new column to the existing DataFrame with the encoded values
    df_Train[LABEL] = le.fit_transform(df_Train['Class_label'].values.ravel())
    # df_Valid[LABEL] = le.fit_transform(df_Valid['Class_label'].values.ravel())
    df_Test[LABEL] = le.fit_transform(df_Test['Class_label'].values.ravel())
    x_train, y_train = create_segments_and_labels(df_Train,TIME_PERIODS,STEP_DISTANCE,N_FEATURES,LABEL)
    print('x_train shape: ', x_train.shape)
    # print(x_train)
    print(x_train.shape[0], 'training samples')
    print('y_train shape: ', y_train.shape)
    # Set input & output dimensions
    num_time_periods, num_sensors = x_train.shape[1], x_train.shape[2]
    print('num_time_periods',num_time_periods)
    print('num_sensors',num_sensors)
    num_classes = le.classes_.size
    print('class_list',list(le.classes_))
    # input_shape = (num_time_periods,num_sensors)
    # print(input_shape)
    input_shape = (num_time_periods,num_sensors)
    #x_train = x_train.reshape(x_train.shape[0], input_shape)
    print('x_train shape:', x_train[0].shape)
    print('input_shape:', input_shape)
    x_train = x_train.astype('float32')
    # x_train = [torch.tensor(arr, dtype=torch.float32) for arr in x_train]
    # y_train = y_train.astype('float32')
    # print(y_train)
    y_train_hot = np_utils.to_categorical(y_train, num_classes)
    print(y_train_hot)
    # y_train_hot= [torch.tensor(arr, dtype=torch.uint8) for arr in y_train_hot]
    print('New y_train shape: ', y_train_hot.shape)
    x_test, y_test = create_segments_and_labels(df_Test,TIME_PERIODS,STEP_DISTANCE,N_FEATURES,LABEL)
    print('x_test shape: ', x_test.shape)
    # print(x_train)
    print(x_test.shape[0], 'testing samples')
    print('y_test shape: ', y_test.shape)
    # Set input_shape / reshape for Keras
    #x_test = x_test.reshape(x_test.shape[0], input_shape)
    x_test = x_test.astype('float32')
    y_test = y_test.astype('float32')
    y_test_hot = np_utils.to_categorical(y_test, num_classes)
    # n_steps, n_length = 20, 25
    # n_steps, n_length= 10, 50
    # n_steps, n_length= 16, 32
    n_length =  400
    n_depth=12
    n_channel=12
    x_train = x_train.reshape(x_train.shape[0], n_length,n_depth)
    print('x_train shape: ', x_train.shape)
    # x_valid = x_valid.reshape(x_valid.shape[0], n_steps, n_length, n_depth)
    # print('x_valid shape: ', x_valid.shape)
    x_test = x_test.reshape(x_test.shape[0],  n_length,n_depth)
    print('x_test shape: ', x_test.shape)
    n_outputs = y_train_hot.shape[1]
    print('n_outputs',n_outputs)
    adam=optimizers.Adam(lr=1e-3, beta_1=0.9, beta_2=0.999, amsgrad=False)
#     sgd=optimizers.SGD(learning_rate=0.1, momentum=0.9, nesterov=False, name='SGD')
    checkpoint_filepath = '/media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5'
#     model.load_weights(checkpoint_filepath) 
    checkpoint_callback = ModelCheckpoint(filepath=checkpoint_filepath,verbose=1, monitor='val_accuracy',save_weights_only=True,save_best_only=True)
    early = EarlyStopping(monitor='val_loss', min_delta=0, patience=100, verbose=0, mode='auto', baseline=None, restore_best_weights=True)
    model.compile(optimizer=adam,loss='categorical_crossentropy',metrics=['accuracy'])
    print(model.summary())
#     tf.keras.utils.plot_model(model, to_file='/media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/olsson/CNN20X10/Model1.png',show_shapes=True,show_layer_names=True,dpi=96)
    csv_logger = CSVLogger('/media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/LSTM_nina_20X100.csv', append=True, separator=';')
    history = model.fit(x_train, y_train_hot, epochs=epochs, batch_size=batch_size, callbacks=[csv_logger,checkpoint_callback,lrate,early],validation_data=(x_test, y_test_hot), verbose=1)
    best_index = history.history['val_accuracy'].index(max(history.history['val_accuracy']))
    print('epoch_number',best_index+1)
    print('train accuracy and validation accuracy', history.history['accuracy'][best_index], history.history['val_accuracy'][best_index])
    model.load_weights(checkpoint_filepath) 
    _, testaccuracy = model.evaluate(x_test, y_test_hot, batch_size=batch_size, verbose=1)
    print('test_accuracy',testaccuracy)
    test_acc.append(testaccuracy)
    print(test_acc)
    test_mean=statistics.mean(test_acc)
    print('test_mean for %d subjects:',i)
    print(test_mean)

/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S1_tr.csv
Number of columns in the dataframe: 13
Number of rows in the dataframe: 2080000

/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S1_tt.csv
Number of columns in the dataframe: 13
Number of rows in the dataframe: 1040000

x_train shape:  (5199, 400, 12)
5199 training samples
y_train shape:  (5199,)
num_time_periods 400
num_sensors 12
class_list [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0]
x_train shape: (400, 12)
input_shape: (400, 12)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
New y_train shape:  (5199, 

Epoch 1/120
163/163 [==============================] - ETA: 0s - loss: 6.2324 - accuracy: 0.0616
Epoch 00001: val_accuracy improved from -inf to 0.19931, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 148s 908ms/step - loss: 6.2324 - accuracy: 0.0616 - val_loss: 5.0986 - val_accuracy: 0.1993 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 4.6579 - accuracy: 0.1789
Epoch 00002: val_accuracy improved from 0.19931 to 0.24971, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 63s 388ms/step - loss: 4.6579 - accuracy: 0.1789 - val_loss: 4.0282 - val_accuracy: 0.2497 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.7857 - accuracy: 0.2468
Epoch 00003: val_accuracy improved from 0.24971 to 0.28742, saving model to /media/na

163/163 [==============================] - ETA: 0s - loss: 0.7991 - accuracy: 0.9465
Epoch 00053: val_accuracy did not improve from 0.34706
163/163 [==============================] - 55s 336ms/step - loss: 0.7991 - accuracy: 0.9465 - val_loss: 4.1538 - val_accuracy: 0.2855 - lr: 1.0000e-04
Epoch 54/120
163/163 [==============================] - ETA: 0s - loss: 0.7764 - accuracy: 0.9454
Epoch 00054: val_accuracy did not improve from 0.34706
163/163 [==============================] - 55s 335ms/step - loss: 0.7764 - accuracy: 0.9454 - val_loss: 4.1886 - val_accuracy: 0.2820 - lr: 1.0000e-04
Epoch 55/120
163/163 [==============================] - ETA: 0s - loss: 0.7506 - accuracy: 0.9508
Epoch 00055: val_accuracy did not improve from 0.34706
163/163 [==============================] - 54s 334ms/step - loss: 0.7506 - accuracy: 0.9508 - val_loss: 4.1247 - val_accuracy: 0.2828 - lr: 1.0000e-04
Epoch 56/120
163/163 [==============================] - ETA: 0s - loss: 0.7238 - accuracy: 0.9552
Epo

Epoch 80/120
163/163 [==============================] - ETA: 0s - loss: 0.4403 - accuracy: 0.9733
Epoch 00080: val_accuracy did not improve from 0.34706
163/163 [==============================] - 54s 333ms/step - loss: 0.4403 - accuracy: 0.9733 - val_loss: 4.2108 - val_accuracy: 0.2740 - lr: 1.0000e-05
Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.4384 - accuracy: 0.9736
Epoch 00081: val_accuracy did not improve from 0.34706
163/163 [==============================] - 54s 333ms/step - loss: 0.4384 - accuracy: 0.9736 - val_loss: 4.2564 - val_accuracy: 0.2759 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.4372 - accuracy: 0.9710
Epoch 00082: val_accuracy did not improve from 0.34706
163/163 [==============================] - 54s 333ms/step - loss: 0.4372 - accuracy: 0.9710 - val_loss: 4.2489 - val_accuracy: 0.2774 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.4347 - accurac

Epoch 107/120
163/163 [==============================] - ETA: 0s - loss: 0.3974 - accuracy: 0.9781
Epoch 00107: val_accuracy did not improve from 0.34706
163/163 [==============================] - 54s 334ms/step - loss: 0.3974 - accuracy: 0.9781 - val_loss: 4.2049 - val_accuracy: 0.2786 - lr: 1.0000e-05
Epoch 108/120
163/163 [==============================] - ETA: 0s - loss: 0.4002 - accuracy: 0.9781
Epoch 00108: val_accuracy did not improve from 0.34706
163/163 [==============================] - 55s 338ms/step - loss: 0.4002 - accuracy: 0.9781 - val_loss: 4.3143 - val_accuracy: 0.2824 - lr: 1.0000e-05
epoch_number 10
train accuracy and validation accuracy 0.4316214621067047 0.3470565676689148
82/82 [==============================] - 6s 72ms/step - loss: 3.0374 - accuracy: 0.3471
test_accuracy 0.3470565676689148
[0.3470565676689148]
test_mean for %d subjects: 1
0.3470565676689148
/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S2_tr.csv
Number of columns 

Epoch 1/120
163/163 [==============================] - ETA: 0s - loss: 4.1134 - accuracy: 0.1235
Epoch 00001: val_accuracy improved from -inf to 0.21547, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 123s 756ms/step - loss: 4.1134 - accuracy: 0.1235 - val_loss: 3.3780 - val_accuracy: 0.2155 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.3822 - accuracy: 0.2064
Epoch 00002: val_accuracy improved from 0.21547 to 0.24086, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 61s 374ms/step - loss: 3.3822 - accuracy: 0.2064 - val_loss: 3.2804 - val_accuracy: 0.2409 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.2493 - accuracy: 0.2539
Epoch 00003: val_accuracy improved from 0.24086 to 0.28396, saving model to /media/na

Epoch 27/120
163/163 [==============================] - ETA: 0s - loss: 1.9961 - accuracy: 0.7028
Epoch 00027: val_accuracy did not improve from 0.31628
163/163 [==============================] - 55s 335ms/step - loss: 1.9961 - accuracy: 0.7028 - val_loss: 4.1264 - val_accuracy: 0.2863 - lr: 0.0010
Epoch 28/120
163/163 [==============================] - ETA: 0s - loss: 1.9516 - accuracy: 0.7086
Epoch 00028: val_accuracy did not improve from 0.31628
163/163 [==============================] - 55s 335ms/step - loss: 1.9516 - accuracy: 0.7086 - val_loss: 4.0652 - val_accuracy: 0.2859 - lr: 0.0010
Epoch 29/120
163/163 [==============================] - ETA: 0s - loss: 1.9638 - accuracy: 0.7163
Epoch 00029: val_accuracy did not improve from 0.31628
163/163 [==============================] - 55s 335ms/step - loss: 1.9638 - accuracy: 0.7163 - val_loss: 4.3025 - val_accuracy: 0.2793 - lr: 0.0010
Epoch 30/120
163/163 [==============================] - ETA: 0s - loss: 1.9450 - accuracy: 0.7215
Ep

Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.5199 - accuracy: 0.9492
Epoch 00081: val_accuracy did not improve from 0.31628
163/163 [==============================] - 55s 336ms/step - loss: 0.5199 - accuracy: 0.9492 - val_loss: 4.2266 - val_accuracy: 0.2639 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.5112 - accuracy: 0.9527
Epoch 00082: val_accuracy did not improve from 0.31628
163/163 [==============================] - 54s 334ms/step - loss: 0.5112 - accuracy: 0.9527 - val_loss: 4.2504 - val_accuracy: 0.2682 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.5116 - accuracy: 0.9517
Epoch 00083: val_accuracy did not improve from 0.31628
163/163 [==============================] - 54s 334ms/step - loss: 0.5116 - accuracy: 0.9517 - val_loss: 4.2416 - val_accuracy: 0.2674 - lr: 1.0000e-05
Epoch 84/120
163/163 [==============================] - ETA: 0s - loss: 0.5121 - accurac

Epoch 108/120
163/163 [==============================] - ETA: 0s - loss: 0.4824 - accuracy: 0.9544
Epoch 00108: val_accuracy did not improve from 0.31628
163/163 [==============================] - 55s 339ms/step - loss: 0.4824 - accuracy: 0.9544 - val_loss: 4.2379 - val_accuracy: 0.2636 - lr: 1.0000e-05
epoch_number 7
train accuracy and validation accuracy 0.351798415184021 0.3162754774093628
82/82 [==============================] - 6s 72ms/step - loss: 3.2337 - accuracy: 0.3163
test_accuracy 0.3162754774093628
[0.3470565676689148, 0.3162754774093628]
test_mean for %d subjects: 2
0.3316660225391388
/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S3_tr.csv
Number of columns in the dataframe: 13
Number of rows in the dataframe: 2080000

/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S3_tt.csv
Number of columns in the dataframe: 13
Number of rows in the dataframe: 1040000

x_train shape:  (5199, 400, 12)
5199 training samples


163/163 [==============================] - ETA: 0s - loss: 4.0066 - accuracy: 0.1287
Epoch 00001: val_accuracy improved from -inf to 0.22162, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 127s 776ms/step - loss: 4.0066 - accuracy: 0.1287 - val_loss: 3.2364 - val_accuracy: 0.2216 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.3139 - accuracy: 0.2189
Epoch 00002: val_accuracy improved from 0.22162 to 0.25317, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 61s 372ms/step - loss: 3.3139 - accuracy: 0.2189 - val_loss: 3.1514 - val_accuracy: 0.2532 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.1747 - accuracy: 0.2745
Epoch 00003: val_accuracy improved from 0.25317 to 0.28973, saving model to /media/naveen/nav/mat

Epoch 26/120
163/163 [==============================] - ETA: 0s - loss: 1.8392 - accuracy: 0.7755
Epoch 00026: val_accuracy did not improve from 0.31666
163/163 [==============================] - 55s 335ms/step - loss: 1.8392 - accuracy: 0.7755 - val_loss: 4.2893 - val_accuracy: 0.2751 - lr: 0.0010
Epoch 27/120
163/163 [==============================] - ETA: 0s - loss: 1.7295 - accuracy: 0.7915
Epoch 00027: val_accuracy did not improve from 0.31666
163/163 [==============================] - 54s 334ms/step - loss: 1.7295 - accuracy: 0.7915 - val_loss: 4.3289 - val_accuracy: 0.2901 - lr: 0.0010
Epoch 28/120
163/163 [==============================] - ETA: 0s - loss: 1.7425 - accuracy: 0.7948
Epoch 00028: val_accuracy did not improve from 0.31666
163/163 [==============================] - 55s 335ms/step - loss: 1.7425 - accuracy: 0.7948 - val_loss: 4.2990 - val_accuracy: 0.2863 - lr: 0.0010
Epoch 29/120
163/163 [==============================] - ETA: 0s - loss: 1.7381 - accuracy: 0.7990
Ep

Epoch 80/120
163/163 [==============================] - ETA: 0s - loss: 0.3944 - accuracy: 0.9763
Epoch 00080: val_accuracy did not improve from 0.31666
163/163 [==============================] - 54s 334ms/step - loss: 0.3944 - accuracy: 0.9763 - val_loss: 4.2578 - val_accuracy: 0.2682 - lr: 1.0000e-05
Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.3906 - accuracy: 0.9773
Epoch 00081: val_accuracy did not improve from 0.31666
163/163 [==============================] - 54s 334ms/step - loss: 0.3906 - accuracy: 0.9773 - val_loss: 4.2961 - val_accuracy: 0.2701 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.3935 - accuracy: 0.9783
Epoch 00082: val_accuracy did not improve from 0.31666
163/163 [==============================] - 54s 333ms/step - loss: 0.3935 - accuracy: 0.9783 - val_loss: 4.2371 - val_accuracy: 0.2724 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.3833 - accurac

x_test shape:  (2599, 400, 12)
2599 testing samples
y_test shape:  (2599,)
x_train shape:  (5199, 400, 12)
x_test shape:  (2599, 400, 12)
n_outputs 52
Model: "wei_mscnn_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main (InputLayer)               [(None, 400, 12)]    0                                            
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_2 (Te [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_4 (Te 

163/163 [==============================] - ETA: 0s - loss: 4.3346 - accuracy: 0.1391
Epoch 00001: val_accuracy improved from -inf to 0.24356, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 124s 763ms/step - loss: 4.3346 - accuracy: 0.1391 - val_loss: 3.3452 - val_accuracy: 0.2436 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.2697 - accuracy: 0.2460
Epoch 00002: val_accuracy improved from 0.24356 to 0.30204, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 61s 374ms/step - loss: 3.2697 - accuracy: 0.2460 - val_loss: 3.0909 - val_accuracy: 0.3020 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.0951 - accuracy: 0.3062
Epoch 00003: val_accuracy improved from 0.30204 to 0.34398, saving model to /media/naveen/nav/mat

Epoch 26/120
163/163 [==============================] - ETA: 0s - loss: 1.6678 - accuracy: 0.7982
Epoch 00026: val_accuracy did not improve from 0.36553
163/163 [==============================] - 54s 334ms/step - loss: 1.6678 - accuracy: 0.7982 - val_loss: 3.9904 - val_accuracy: 0.3367 - lr: 0.0010
Epoch 27/120
163/163 [==============================] - ETA: 0s - loss: 1.5955 - accuracy: 0.8184
Epoch 00027: val_accuracy did not improve from 0.36553
163/163 [==============================] - 55s 335ms/step - loss: 1.5955 - accuracy: 0.8184 - val_loss: 3.9613 - val_accuracy: 0.3278 - lr: 0.0010
Epoch 28/120
163/163 [==============================] - ETA: 0s - loss: 1.6209 - accuracy: 0.8157
Epoch 00028: val_accuracy did not improve from 0.36553
163/163 [==============================] - 55s 335ms/step - loss: 1.6209 - accuracy: 0.8157 - val_loss: 3.9852 - val_accuracy: 0.3278 - lr: 0.0010
Epoch 29/120
163/163 [==============================] - ETA: 0s - loss: 1.5936 - accuracy: 0.8252
Ep

Epoch 80/120
163/163 [==============================] - ETA: 0s - loss: 0.3894 - accuracy: 0.9786
Epoch 00080: val_accuracy did not improve from 0.36553
163/163 [==============================] - 54s 334ms/step - loss: 0.3894 - accuracy: 0.9786 - val_loss: 3.9453 - val_accuracy: 0.3190 - lr: 1.0000e-05
Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.3924 - accuracy: 0.9775
Epoch 00081: val_accuracy did not improve from 0.36553
163/163 [==============================] - 55s 335ms/step - loss: 0.3924 - accuracy: 0.9775 - val_loss: 3.8908 - val_accuracy: 0.3174 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.3841 - accuracy: 0.9771
Epoch 00082: val_accuracy did not improve from 0.36553
163/163 [==============================] - 54s 334ms/step - loss: 0.3841 - accuracy: 0.9771 - val_loss: 3.8456 - val_accuracy: 0.3228 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.3844 - accurac

epoch_number 15
train accuracy and validation accuracy 0.677437961101532 0.3655252158641815
82/82 [==============================] - 6s 75ms/step - loss: 3.4805 - accuracy: 0.3655
test_accuracy 0.3655252158641815
[0.3470565676689148, 0.3162754774093628, 0.3166602551937103, 0.3655252158641815]
test_mean for %d subjects: 4
0.33637937903404236
/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S5_tr.csv
Number of columns in the dataframe: 13
Number of rows in the dataframe: 2080000

/media/naveen/nav/mat_codes/nina_DB4_codes/naveen_prep_nlw/sub_wise_process_TT/S5_tt.csv
Number of columns in the dataframe: 13
Number of rows in the dataframe: 1040000

x_train shape:  (5199, 400, 12)
5199 training samples
y_train shape:  (5199,)
num_time_periods 400
num_sensors 12
class_list [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34

163/163 [==============================] - ETA: 0s - loss: 4.8120 - accuracy: 0.1393
Epoch 00001: val_accuracy improved from -inf to 0.26048, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 123s 752ms/step - loss: 4.8120 - accuracy: 0.1393 - val_loss: 3.5060 - val_accuracy: 0.2605 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.4584 - accuracy: 0.2651
Epoch 00002: val_accuracy improved from 0.26048 to 0.30743, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 61s 376ms/step - loss: 3.4584 - accuracy: 0.2651 - val_loss: 3.1837 - val_accuracy: 0.3074 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.1882 - accuracy: 0.3226
Epoch 00003: val_accuracy improved from 0.30743 to 0.33359, saving model to /media/naveen/nav/mat

163/163 [==============================] - ETA: 0s - loss: 0.6847 - accuracy: 0.9694
Epoch 00053: val_accuracy did not improve from 0.37822
163/163 [==============================] - 55s 334ms/step - loss: 0.6847 - accuracy: 0.9694 - val_loss: 4.0118 - val_accuracy: 0.3359 - lr: 1.0000e-04
Epoch 54/120
163/163 [==============================] - ETA: 0s - loss: 0.6801 - accuracy: 0.9652
Epoch 00054: val_accuracy did not improve from 0.37822
163/163 [==============================] - 55s 336ms/step - loss: 0.6801 - accuracy: 0.9652 - val_loss: 4.0813 - val_accuracy: 0.3290 - lr: 1.0000e-04
Epoch 55/120
163/163 [==============================] - ETA: 0s - loss: 0.6506 - accuracy: 0.9711
Epoch 00055: val_accuracy did not improve from 0.37822
163/163 [==============================] - 55s 336ms/step - loss: 0.6506 - accuracy: 0.9711 - val_loss: 4.0162 - val_accuracy: 0.3363 - lr: 1.0000e-04
Epoch 56/120
163/163 [==============================] - ETA: 0s - loss: 0.6472 - accuracy: 0.9658
Epo

Epoch 80/120
163/163 [==============================] - ETA: 0s - loss: 0.3912 - accuracy: 0.9800
Epoch 00080: val_accuracy did not improve from 0.37822
163/163 [==============================] - 55s 337ms/step - loss: 0.3912 - accuracy: 0.9800 - val_loss: 3.9725 - val_accuracy: 0.3363 - lr: 1.0000e-05
Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.3949 - accuracy: 0.9788
Epoch 00081: val_accuracy did not improve from 0.37822
163/163 [==============================] - 54s 334ms/step - loss: 0.3949 - accuracy: 0.9788 - val_loss: 3.9883 - val_accuracy: 0.3401 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.3879 - accuracy: 0.9819
Epoch 00082: val_accuracy did not improve from 0.37822
163/163 [==============================] - 55s 335ms/step - loss: 0.3879 - accuracy: 0.9819 - val_loss: 3.9686 - val_accuracy: 0.3344 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.3893 - accurac

Number of columns in the dataframe: 13
Number of rows in the dataframe: 1040000

x_train shape:  (5199, 400, 12)
5199 training samples
y_train shape:  (5199,)
num_time_periods 400
num_sensors 12
class_list [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0]
x_train shape: (400, 12)
input_shape: (400, 12)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]
New y_train shape:  (5199, 52)
x_test shape:  (2599, 400, 12)
2599 testing samples
y_test shape:  (2599,)
x_train shape:  (5199, 400, 12)
x_test shape:  (2599, 400, 12)
n_outputs 52
Model: "wei_mscnn_model"
_______________________________________________________________________________

Epoch 1/120
163/163 [==============================] - ETA: 0s - loss: 4.6067 - accuracy: 0.1402
Epoch 00001: val_accuracy improved from -inf to 0.26510, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 132s 807ms/step - loss: 4.6067 - accuracy: 0.1402 - val_loss: 3.4383 - val_accuracy: 0.2651 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.3854 - accuracy: 0.2581
Epoch 00002: val_accuracy improved from 0.26510 to 0.32628, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 61s 376ms/step - loss: 3.3854 - accuracy: 0.2581 - val_loss: 3.1069 - val_accuracy: 0.3263 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.0660 - accuracy: 0.3372
Epoch 00003: val_accuracy did not improve from 0.32628
163/163 [=====================

Epoch 27/120
163/163 [==============================] - ETA: 0s - loss: 1.4750 - accuracy: 0.8432
Epoch 00027: val_accuracy did not improve from 0.39169
163/163 [==============================] - 54s 334ms/step - loss: 1.4750 - accuracy: 0.8432 - val_loss: 3.9142 - val_accuracy: 0.3617 - lr: 0.0010
Epoch 28/120
163/163 [==============================] - ETA: 0s - loss: 1.4557 - accuracy: 0.8536
Epoch 00028: val_accuracy did not improve from 0.39169
163/163 [==============================] - 54s 334ms/step - loss: 1.4557 - accuracy: 0.8536 - val_loss: 4.0007 - val_accuracy: 0.3590 - lr: 0.0010
Epoch 29/120
163/163 [==============================] - ETA: 0s - loss: 1.5155 - accuracy: 0.8427
Epoch 00029: val_accuracy did not improve from 0.39169
163/163 [==============================] - 54s 334ms/step - loss: 1.5155 - accuracy: 0.8427 - val_loss: 4.0440 - val_accuracy: 0.3528 - lr: 0.0010
Epoch 30/120
163/163 [==============================] - ETA: 0s - loss: 1.5046 - accuracy: 0.8517
Ep

Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.3986 - accuracy: 0.9840
Epoch 00081: val_accuracy did not improve from 0.39169
163/163 [==============================] - 54s 333ms/step - loss: 0.3986 - accuracy: 0.9840 - val_loss: 3.7893 - val_accuracy: 0.3574 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.3939 - accuracy: 0.9831
Epoch 00082: val_accuracy did not improve from 0.39169
163/163 [==============================] - 54s 333ms/step - loss: 0.3939 - accuracy: 0.9831 - val_loss: 3.7467 - val_accuracy: 0.3513 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.4021 - accuracy: 0.9798
Epoch 00083: val_accuracy did not improve from 0.39169
163/163 [==============================] - 54s 332ms/step - loss: 0.4021 - accuracy: 0.9798 - val_loss: 3.7811 - val_accuracy: 0.3486 - lr: 1.0000e-05
Epoch 84/120
163/163 [==============================] - ETA: 0s - loss: 0.3951 - accurac

x_test shape:  (2599, 400, 12)
2599 testing samples
y_test shape:  (2599,)
x_train shape:  (5199, 400, 12)
x_test shape:  (2599, 400, 12)
n_outputs 52
Model: "wei_mscnn_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main (InputLayer)               [(None, 400, 12)]    0                                            
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_2 (Te [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_4 (Te 

163/163 [==============================] - ETA: 0s - loss: 4.5955 - accuracy: 0.1154
Epoch 00001: val_accuracy improved from -inf to 0.20700, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 123s 757ms/step - loss: 4.5955 - accuracy: 0.1154 - val_loss: 3.6509 - val_accuracy: 0.2070 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.5396 - accuracy: 0.2206
Epoch 00002: val_accuracy improved from 0.20700 to 0.24471, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 62s 378ms/step - loss: 3.5396 - accuracy: 0.2206 - val_loss: 3.3707 - val_accuracy: 0.2447 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.3431 - accuracy: 0.2766
Epoch 00003: val_accuracy improved from 0.24471 to 0.26395, saving model to /media/naveen/nav/mat

Epoch 27/120
163/163 [==============================] - ETA: 0s - loss: 1.7848 - accuracy: 0.7932
Epoch 00027: val_accuracy did not improve from 0.30012
163/163 [==============================] - 55s 336ms/step - loss: 1.7848 - accuracy: 0.7932 - val_loss: 4.6134 - val_accuracy: 0.2724 - lr: 0.0010
Epoch 28/120
163/163 [==============================] - ETA: 0s - loss: 1.7581 - accuracy: 0.7988
Epoch 00028: val_accuracy did not improve from 0.30012
163/163 [==============================] - 54s 333ms/step - loss: 1.7581 - accuracy: 0.7988 - val_loss: 4.6971 - val_accuracy: 0.2705 - lr: 0.0010
Epoch 29/120
163/163 [==============================] - ETA: 0s - loss: 1.7573 - accuracy: 0.7928
Epoch 00029: val_accuracy did not improve from 0.30012
163/163 [==============================] - 55s 335ms/step - loss: 1.7573 - accuracy: 0.7928 - val_loss: 4.8100 - val_accuracy: 0.2597 - lr: 0.0010
Epoch 30/120
163/163 [==============================] - ETA: 0s - loss: 1.6986 - accuracy: 0.8221
Ep

Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.5045 - accuracy: 0.9738
Epoch 00081: val_accuracy did not improve from 0.30012
163/163 [==============================] - 57s 350ms/step - loss: 0.5045 - accuracy: 0.9738 - val_loss: 4.6943 - val_accuracy: 0.2555 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.4996 - accuracy: 0.9761
Epoch 00082: val_accuracy did not improve from 0.30012
163/163 [==============================] - 56s 345ms/step - loss: 0.4996 - accuracy: 0.9761 - val_loss: 4.7478 - val_accuracy: 0.2551 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.4983 - accuracy: 0.9760
Epoch 00083: val_accuracy did not improve from 0.30012
163/163 [==============================] - 57s 347ms/step - loss: 0.4983 - accuracy: 0.9760 - val_loss: 4.7066 - val_accuracy: 0.2613 - lr: 1.0000e-05
Epoch 84/120
163/163 [==============================] - ETA: 0s - loss: 0.4990 - accurac

Epoch 1/120
163/163 [==============================] - ETA: 0s - loss: 3.9485 - accuracy: 0.1602
Epoch 00001: val_accuracy improved from -inf to 0.28626, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 126s 774ms/step - loss: 3.9485 - accuracy: 0.1602 - val_loss: 3.2204 - val_accuracy: 0.2863 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.1716 - accuracy: 0.2835
Epoch 00002: val_accuracy improved from 0.28626 to 0.31012, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 63s 389ms/step - loss: 3.1716 - accuracy: 0.2835 - val_loss: 3.0738 - val_accuracy: 0.3101 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.0055 - accuracy: 0.3393
Epoch 00003: val_accuracy improved from 0.31012 to 0.34436, saving model to /media/na

163/163 [==============================] - ETA: 0s - loss: 0.7625 - accuracy: 0.9617
Epoch 00053: val_accuracy did not improve from 0.37861
163/163 [==============================] - 55s 335ms/step - loss: 0.7625 - accuracy: 0.9617 - val_loss: 4.1501 - val_accuracy: 0.3217 - lr: 1.0000e-04
Epoch 54/120
163/163 [==============================] - ETA: 0s - loss: 0.7357 - accuracy: 0.9658
Epoch 00054: val_accuracy did not improve from 0.37861
163/163 [==============================] - 55s 336ms/step - loss: 0.7357 - accuracy: 0.9658 - val_loss: 4.1520 - val_accuracy: 0.3290 - lr: 1.0000e-04
Epoch 55/120
163/163 [==============================] - ETA: 0s - loss: 0.7169 - accuracy: 0.9656
Epoch 00055: val_accuracy did not improve from 0.37861
163/163 [==============================] - 55s 335ms/step - loss: 0.7169 - accuracy: 0.9656 - val_loss: 4.1676 - val_accuracy: 0.3224 - lr: 1.0000e-04
Epoch 56/120
163/163 [==============================] - ETA: 0s - loss: 0.7029 - accuracy: 0.9673
Epo

Epoch 80/120
163/163 [==============================] - ETA: 0s - loss: 0.4335 - accuracy: 0.9802
Epoch 00080: val_accuracy did not improve from 0.37861
163/163 [==============================] - 55s 335ms/step - loss: 0.4335 - accuracy: 0.9802 - val_loss: 4.1408 - val_accuracy: 0.3259 - lr: 1.0000e-05
Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.4322 - accuracy: 0.9808
Epoch 00081: val_accuracy did not improve from 0.37861
163/163 [==============================] - 55s 336ms/step - loss: 0.4322 - accuracy: 0.9808 - val_loss: 4.1229 - val_accuracy: 0.3263 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.4285 - accuracy: 0.9804
Epoch 00082: val_accuracy did not improve from 0.37861
163/163 [==============================] - 55s 335ms/step - loss: 0.4285 - accuracy: 0.9804 - val_loss: 4.1108 - val_accuracy: 0.3267 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.4334 - accurac

x_test shape:  (2599, 400, 12)
2599 testing samples
y_test shape:  (2599,)
x_train shape:  (5199, 400, 12)
x_test shape:  (2599, 400, 12)
n_outputs 52
Model: "wei_mscnn_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main (InputLayer)               [(None, 400, 12)]    0                                            
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_2 (Te [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_4 (Te 

Epoch 1/120
163/163 [==============================] - ETA: 0s - loss: 4.3575 - accuracy: 0.1377
Epoch 00001: val_accuracy improved from -inf to 0.24279, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 122s 747ms/step - loss: 4.3575 - accuracy: 0.1377 - val_loss: 3.4640 - val_accuracy: 0.2428 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.3582 - accuracy: 0.2527
Epoch 00002: val_accuracy improved from 0.24279 to 0.29742, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 61s 373ms/step - loss: 3.3582 - accuracy: 0.2527 - val_loss: 3.1800 - val_accuracy: 0.2974 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.0820 - accuracy: 0.3187
Epoch 00003: val_accuracy improved from 0.29742 to 0.32051, saving model to /media/na

163/163 [==============================] - ETA: 0s - loss: 0.7744 - accuracy: 0.9644
Epoch 00053: val_accuracy did not improve from 0.34436
163/163 [==============================] - 54s 332ms/step - loss: 0.7744 - accuracy: 0.9644 - val_loss: 4.2675 - val_accuracy: 0.3055 - lr: 1.0000e-04
Epoch 54/120
163/163 [==============================] - ETA: 0s - loss: 0.7640 - accuracy: 0.9615
Epoch 00054: val_accuracy did not improve from 0.34436
163/163 [==============================] - 54s 332ms/step - loss: 0.7640 - accuracy: 0.9615 - val_loss: 4.2701 - val_accuracy: 0.3028 - lr: 1.0000e-04
Epoch 55/120
163/163 [==============================] - ETA: 0s - loss: 0.7452 - accuracy: 0.9663
Epoch 00055: val_accuracy did not improve from 0.34436
163/163 [==============================] - 54s 334ms/step - loss: 0.7452 - accuracy: 0.9663 - val_loss: 4.2487 - val_accuracy: 0.3070 - lr: 1.0000e-04
Epoch 56/120
163/163 [==============================] - ETA: 0s - loss: 0.7288 - accuracy: 0.9660
Epo

Epoch 80/120
163/163 [==============================] - ETA: 0s - loss: 0.4536 - accuracy: 0.9786
Epoch 00080: val_accuracy did not improve from 0.34436
163/163 [==============================] - 54s 332ms/step - loss: 0.4536 - accuracy: 0.9786 - val_loss: 4.3429 - val_accuracy: 0.2943 - lr: 1.0000e-05
Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.4601 - accuracy: 0.9765
Epoch 00081: val_accuracy did not improve from 0.34436
163/163 [==============================] - 54s 331ms/step - loss: 0.4601 - accuracy: 0.9765 - val_loss: 4.3580 - val_accuracy: 0.3005 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.4497 - accuracy: 0.9806
Epoch 00082: val_accuracy did not improve from 0.34436
163/163 [==============================] - 54s 331ms/step - loss: 0.4497 - accuracy: 0.9806 - val_loss: 4.2872 - val_accuracy: 0.3017 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.4524 - accurac

x_test shape:  (2599, 400, 12)
2599 testing samples
y_test shape:  (2599,)
x_train shape:  (5199, 400, 12)
x_test shape:  (2599, 400, 12)
n_outputs 52
Model: "wei_mscnn_model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
main (InputLayer)               [(None, 400, 12)]    0                                            
__________________________________________________________________________________________________
tf_op_layer_strided_slice (Tens [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_2 (Te [(None, 400)]        0           main[0][0]                       
__________________________________________________________________________________________________
tf_op_layer_strided_slice_4 (Te 

Epoch 1/120
163/163 [==============================] - ETA: 0s - loss: 4.7360 - accuracy: 0.1118
Epoch 00001: val_accuracy improved from -inf to 0.21047, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 123s 755ms/step - loss: 4.7360 - accuracy: 0.1118 - val_loss: 3.7439 - val_accuracy: 0.2105 - lr: 0.0010
Epoch 2/120
163/163 [==============================] - ETA: 0s - loss: 3.6712 - accuracy: 0.2114
Epoch 00002: val_accuracy improved from 0.21047 to 0.24933, saving model to /media/naveen/nav/mat_codes/nina_DB1_codes/nina_prep_python/wei_DB4_20X10/checkpoint.hdf5
163/163 [==============================] - 60s 367ms/step - loss: 3.6712 - accuracy: 0.2114 - val_loss: 3.4454 - val_accuracy: 0.2493 - lr: 0.0010
Epoch 3/120
163/163 [==============================] - ETA: 0s - loss: 3.3733 - accuracy: 0.2751
Epoch 00003: val_accuracy did not improve from 0.24933
163/163 [=====================

Epoch 27/120
163/163 [==============================] - ETA: 0s - loss: 1.7414 - accuracy: 0.8113
Epoch 00027: val_accuracy did not improve from 0.27241
163/163 [==============================] - 61s 372ms/step - loss: 1.7414 - accuracy: 0.8113 - val_loss: 5.0619 - val_accuracy: 0.2378 - lr: 0.0010
Epoch 28/120
163/163 [==============================] - ETA: 0s - loss: 1.6601 - accuracy: 0.8334
Epoch 00028: val_accuracy did not improve from 0.27241
163/163 [==============================] - 61s 377ms/step - loss: 1.6601 - accuracy: 0.8334 - val_loss: 5.1141 - val_accuracy: 0.2297 - lr: 0.0010
Epoch 29/120
163/163 [==============================] - ETA: 0s - loss: 1.6257 - accuracy: 0.8402
Epoch 00029: val_accuracy did not improve from 0.27241
163/163 [==============================] - 58s 353ms/step - loss: 1.6257 - accuracy: 0.8402 - val_loss: 5.0519 - val_accuracy: 0.2301 - lr: 0.0010
Epoch 30/120
163/163 [==============================] - ETA: 0s - loss: 1.5974 - accuracy: 0.8430
Ep

Epoch 81/120
163/163 [==============================] - ETA: 0s - loss: 0.5273 - accuracy: 0.9796
Epoch 00081: val_accuracy did not improve from 0.27241
163/163 [==============================] - 57s 353ms/step - loss: 0.5273 - accuracy: 0.9796 - val_loss: 5.1162 - val_accuracy: 0.2305 - lr: 1.0000e-05
Epoch 82/120
163/163 [==============================] - ETA: 0s - loss: 0.5331 - accuracy: 0.9752
Epoch 00082: val_accuracy did not improve from 0.27241
163/163 [==============================] - 56s 345ms/step - loss: 0.5331 - accuracy: 0.9752 - val_loss: 5.1146 - val_accuracy: 0.2316 - lr: 1.0000e-05
Epoch 83/120
163/163 [==============================] - ETA: 0s - loss: 0.5306 - accuracy: 0.9765
Epoch 00083: val_accuracy did not improve from 0.27241
163/163 [==============================] - 57s 347ms/step - loss: 0.5306 - accuracy: 0.9765 - val_loss: 5.0830 - val_accuracy: 0.2312 - lr: 1.0000e-05
Epoch 84/120
163/163 [==============================] - ETA: 0s - loss: 0.5317 - accurac

KeyboardInterrupt: 

In [ ]:
statistics.mean(test_acc)